import { N, U, step, db } from "./lib";
const ds = await import("@/lib/distributions.server");
const OLD = "ae61d9aa-7c81-4778-8fa3-e4a167ed574f";
const d = await db();
await step("supersede batch 1: approved without bound destinations (pre-fix gap), no money recorded", () => ds.supersedeDistribution(U.rev, OLD, "[QA] Final approval was granted before payout destinations were bound; re-proposing under the new destination gate."));
const b: any = await step("distribution 1b proposed on July basis (preparer)", () => ds.proposeDistribution(U.prep, { offeringId: N, distributionType: "return_of_capital" as any, declaredAmountCents: 50_000_000, title: "[QA] Distribution 1b", purpose: "[QA] Return of capital", recordDate: "2026-08-20", effectiveDate: "2026-08-25", paymentDate: "2026-08-28", allocationRunId: "3f6e6ad8-29e3-4464-a7e3-9bd0e7d95186" }));
const B = b.batchId;
console.log("NEWBATCH", B, JSON.stringify((await d.from("distribution_batches").select("basis_stale,basis_as_of").eq("id", B).single()).data));
await step("1b request (preparer)", () => ds.requestDistribution(U.prep, B));
await step("1b review (reviewer)", () => ds.reviewDistribution(U.rev, B));
await step("1b manager approval", () => ds.managerApproveDistribution(U.mgr, B));
await step("1b final approval BLOCKED (stale basis)", () => ds.finalApproveDistribution(U.appr, B), true);
await step("1b stale basis approved with reason (reviewer)", () => ds.approveStaleBasis(U.rev, B, "[QA] Ownership unchanged: call 2 was split pro rata by commitment (40/30/20/10), so July percentages still hold."));
await step("1b final approval BLOCKED (withholding)", () => ds.finalApproveDistribution(U.appr, B), true);
const { data: lines } = await d.from("distribution_lines").select("id,display_name,investor_user_id,withholding_status").eq("batch_id", B);
for (const l of lines ?? []) if (l.withholding_status === "review_required") await step(`1b withholding $0 ${l.display_name} (reviewer)`, () => ds.decideLineWithholding(U.rev, { lineId: l.id, amountCents: 0, reason: "[QA] Return of capital to synthetic US person; no withholding per test policy (tax adviser sign-off required for real funds)." }));
await step("1b batch withholding review (approver)", () => ds.reviewDistributionWithholding(U.appr, B));
await step("1b final approval BLOCKED (payment destinations)", () => ds.finalApproveDistribution(U.appr, B), true);
for (const l of lines ?? []) await step(`1b ${l.display_name} confirms approved destination (investor)`, () => ds.investorConfirmDistribution(l.investor_user_id, l.id));
await step("1b final approval (approver)", () => ds.finalApproveDistribution(U.appr, B));
