import { N, U, step, db } from "./lib";
const v = await import("@/lib/valuation.server");
const a5 = await import("@/lib/accounting-phase5.server");
const asset: any = await step("portfolio asset Alpha $2M cost (preparer)", () => v.upsertPortfolioAsset(U.prep, { offeringId: N, issuerName: "[QA] Portfolio Company Alpha", assetName: "[QA] Alpha Series A Preferred", assetClass: "private_preferred" as any, instrument: "preferred_equity", quantity: 1_000_000, ownershipPct: 8, acquisitionDate: "2026-07-20", costBasisCents: 200_000_000 }));
const assetId = asset?.id ?? asset?.assetId;
const val: any = await step("July valuation $2.4M proposed (manager)", () => v.proposeValuation(U.mgr, { assetId, valuationDate: "2026-07-31", effectiveDate: "2026-07-31", valueCents: 240_000_000, quantity: 1_000_000, methodology: "manager_mark" as any, sourceType: "manager_mark" as any, source: "[QA] GP mark", sourceDate: "2026-07-31" }));
const vid = val?.id ?? val?.valuationId;
await step("submit without evidence is blocked (M9)", () => v.submitValuation(U.mgr, vid), true);
await step("attach synthetic evidence (manager)", () => v.addValuationEvidence(U.mgr, { valuationId: vid, kind: "other", title: "[QA] Synthetic term sheet summary", structured: { synthetic: true, pricePerShareCents: 240 } }));
await step("submit valuation (manager)", () => v.submitValuation(U.mgr, vid));
await step("manager cannot approve own valuation", () => v.decideValuation(U.mgr, { valuationId: vid, action: "approve" }), true);
await step("approve valuation (reviewer)", () => v.decideValuation(U.rev, { valuationId: vid, action: "approve" }));
await step("make effective (approver)", () => v.decideValuation(U.appr, { valuationId: vid, action: "make_effective" }));
const j: any = await step("prepare valuation journal (preparer)", () => v.prepareValuationJournal(U.prep, vid));
const e = j?.journalEntryId;
await step("valuation journal reviewed (reviewer)", () => a5.advanceEntry(U.rev, { offeringId: N, entryId: e, to: "reviewed" }));
await step("valuation journal approved (approver)", () => a5.advanceEntry(U.appr, { offeringId: N, entryId: e, to: "approved" }));
await step("valuation journal posted (preparer)", () => a5.advanceEntry(U.prep, { offeringId: N, entryId: e, to: "posted" }));
const d = await db();
const { data: lines } = await d.from("journal_lines").select("debit_cents,credit_cents,account_id").eq("entry_id", e);
console.log("VALJ", JSON.stringify(lines));
