/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ManagerLoginRouteImport } from './routes/manager-login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedWireRouteImport } from './routes/_authenticated/wire'
import { Route as AuthenticatedWireConfirmationRouteImport } from './routes/_authenticated/wire-confirmation'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminApplicationIdRouteImport } from './routes/_authenticated/admin.$applicationId'
import { Route as AuthenticatedAdminAccessRouteImport } from './routes/_authenticated/admin.access'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin.activity'
import { Route as AuthenticatedAdminDocumentLogRouteImport } from './routes/_authenticated/admin.document-log'
import { Route as AuthenticatedAdminEmailPreviewRouteImport } from './routes/_authenticated/admin.email-preview'
import { Route as AuthenticatedAdminFundingRouteImport } from './routes/_authenticated/admin.funding'
import { Route as AuthenticatedAdminFundsRouteImport } from './routes/_authenticated/admin.funds'
import { Route as AuthenticatedAdminFunnelRouteImport } from './routes/_authenticated/admin.funnel'
import { Route as AuthenticatedAdminNewApplicationRouteImport } from './routes/_authenticated/admin.new-application'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin.security'
import { Route as AuthenticatedAdminSetupRouteImport } from './routes/_authenticated/admin.setup'
import { Route as AuthenticatedAdminWireRouteImport } from './routes/_authenticated/admin.wire'
import { Route as AuthenticatedDiligenceIndexRouteImport } from './routes/_authenticated/diligence.index'
import { Route as AuthenticatedDiligenceOfferingIdRouteImport } from './routes/_authenticated/diligence.$offeringId'
import { Route as AuthenticatedManagerIndexRouteImport } from './routes/_authenticated/manager.index'
import { Route as AuthenticatedManagerApplicationIdRouteImport } from './routes/_authenticated/manager.$applicationId'
import { Route as AuthenticatedManagerActivityRouteImport } from './routes/_authenticated/manager.activity'
import { Route as AuthenticatedManagerClosingRouteImport } from './routes/_authenticated/manager.closing'
import { Route as AuthenticatedManagerDiligenceRouteImport } from './routes/_authenticated/manager.diligence'
import { Route as AuthenticatedManagerDocumentsRouteImport } from './routes/_authenticated/manager.documents'
import { Route as AuthenticatedManagerInboxRouteImport } from './routes/_authenticated/manager.inbox'
import { Route as AuthenticatedManagerInvestorsRouteImport } from './routes/_authenticated/manager.investors'
import { Route as AuthenticatedManagerOnboardingRouteImport } from './routes/_authenticated/manager.onboarding'
import { Route as AuthenticatedManagerProfileRouteImport } from './routes/_authenticated/manager.profile'
import { Route as AuthenticatedManagerTimelineRouteImport } from './routes/_authenticated/manager.timeline'
import { Route as AuthenticatedManagerWiresRouteImport } from './routes/_authenticated/manager.wires'
import { Route as AuthenticatedOnboardingAccreditationRouteImport } from './routes/_authenticated/onboarding.accreditation'
import { Route as AuthenticatedOnboardingAmlRouteImport } from './routes/_authenticated/onboarding.aml'
import { Route as AuthenticatedOnboardingDocumentsRouteImport } from './routes/_authenticated/onboarding.documents'
import { Route as AuthenticatedOnboardingFundingRouteImport } from './routes/_authenticated/onboarding.funding'
import { Route as AuthenticatedOnboardingKycRouteImport } from './routes/_authenticated/onboarding.kyc'
import { Route as ApiPublicLoginAttemptRouteImport } from './routes/api/public/login-attempt'
import { Route as LovableEmailEventsRouteImport } from './routes/lovable/email/events'
import { Route as AuthenticatedAdminFundFundIdRouteImport } from './routes/_authenticated/admin.fund.$fundId'
import { Route as AuthenticatedAdminPacketFundIdRouteImport } from './routes/_authenticated/admin.packet.$fundId'
import { Route as ApiPublicEmailClickRouteImport } from './routes/api/public/email/click'
import { Route as ApiPublicEmailOpenRouteImport } from './routes/api/public/email/open'
import { Route as ApiPublicNotifyDrainRouteImport } from './routes/api/public/notify/drain'
import { Route as ApiPublicPacketTokenRouteImport } from './routes/api/public/packet/$token'
import { Route as ApiPublicWebhooksBoxSignRouteImport } from './routes/api/public/webhooks/box-sign'
import { Route as ApiPublicWebhooksDiditRouteImport } from './routes/api/public/webhooks/didit'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerLoginRoute = ManagerLoginRouteImport.update({
  id: '/manager-login',
  path: '/manager-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWireRoute = AuthenticatedWireRouteImport.update({
  id: '/wire',
  path: '/wire',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWireConfirmationRoute =
  AuthenticatedWireConfirmationRouteImport.update({
    id: '/wire-confirmation',
    path: '/wire-confirmation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminApplicationIdRoute =
  AuthenticatedAdminApplicationIdRouteImport.update({
    id: '/admin/$applicationId',
    path: '/admin/$applicationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAccessRoute =
  AuthenticatedAdminAccessRouteImport.update({
    id: '/admin/access',
    path: '/admin/access',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/admin/activity',
    path: '/admin/activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDocumentLogRoute =
  AuthenticatedAdminDocumentLogRouteImport.update({
    id: '/admin/document-log',
    path: '/admin/document-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmailPreviewRoute =
  AuthenticatedAdminEmailPreviewRouteImport.update({
    id: '/admin/email-preview',
    path: '/admin/email-preview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFundingRoute =
  AuthenticatedAdminFundingRouteImport.update({
    id: '/admin/funding',
    path: '/admin/funding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFundsRoute = AuthenticatedAdminFundsRouteImport.update({
  id: '/admin/funds',
  path: '/admin/funds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminFunnelRoute =
  AuthenticatedAdminFunnelRouteImport.update({
    id: '/admin/funnel',
    path: '/admin/funnel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNewApplicationRoute =
  AuthenticatedAdminNewApplicationRouteImport.update({
    id: '/admin/new-application',
    path: '/admin/new-application',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/admin/security',
    path: '/admin/security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSetupRoute = AuthenticatedAdminSetupRouteImport.update({
  id: '/admin/setup',
  path: '/admin/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminWireRoute = AuthenticatedAdminWireRouteImport.update({
  id: '/admin/wire',
  path: '/admin/wire',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiligenceIndexRoute =
  AuthenticatedDiligenceIndexRouteImport.update({
    id: '/diligence/',
    path: '/diligence/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiligenceOfferingIdRoute =
  AuthenticatedDiligenceOfferingIdRouteImport.update({
    id: '/diligence/$offeringId',
    path: '/diligence/$offeringId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerIndexRoute =
  AuthenticatedManagerIndexRouteImport.update({
    id: '/manager/',
    path: '/manager/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerApplicationIdRoute =
  AuthenticatedManagerApplicationIdRouteImport.update({
    id: '/manager/$applicationId',
    path: '/manager/$applicationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerActivityRoute =
  AuthenticatedManagerActivityRouteImport.update({
    id: '/manager/activity',
    path: '/manager/activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerClosingRoute =
  AuthenticatedManagerClosingRouteImport.update({
    id: '/manager/closing',
    path: '/manager/closing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerDiligenceRoute =
  AuthenticatedManagerDiligenceRouteImport.update({
    id: '/manager/diligence',
    path: '/manager/diligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerDocumentsRoute =
  AuthenticatedManagerDocumentsRouteImport.update({
    id: '/manager/documents',
    path: '/manager/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerInboxRoute =
  AuthenticatedManagerInboxRouteImport.update({
    id: '/manager/inbox',
    path: '/manager/inbox',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerInvestorsRoute =
  AuthenticatedManagerInvestorsRouteImport.update({
    id: '/manager/investors',
    path: '/manager/investors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerOnboardingRoute =
  AuthenticatedManagerOnboardingRouteImport.update({
    id: '/manager/onboarding',
    path: '/manager/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerProfileRoute =
  AuthenticatedManagerProfileRouteImport.update({
    id: '/manager/profile',
    path: '/manager/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerTimelineRoute =
  AuthenticatedManagerTimelineRouteImport.update({
    id: '/manager/timeline',
    path: '/manager/timeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerWiresRoute =
  AuthenticatedManagerWiresRouteImport.update({
    id: '/manager/wires',
    path: '/manager/wires',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingAccreditationRoute =
  AuthenticatedOnboardingAccreditationRouteImport.update({
    id: '/onboarding/accreditation',
    path: '/onboarding/accreditation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingAmlRoute =
  AuthenticatedOnboardingAmlRouteImport.update({
    id: '/onboarding/aml',
    path: '/onboarding/aml',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingDocumentsRoute =
  AuthenticatedOnboardingDocumentsRouteImport.update({
    id: '/onboarding/documents',
    path: '/onboarding/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingFundingRoute =
  AuthenticatedOnboardingFundingRouteImport.update({
    id: '/onboarding/funding',
    path: '/onboarding/funding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingKycRoute =
  AuthenticatedOnboardingKycRouteImport.update({
    id: '/onboarding/kyc',
    path: '/onboarding/kyc',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicLoginAttemptRoute = ApiPublicLoginAttemptRouteImport.update({
  id: '/api/public/login-attempt',
  path: '/api/public/login-attempt',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailEventsRoute = LovableEmailEventsRouteImport.update({
  id: '/lovable/email/events',
  path: '/lovable/email/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminFundFundIdRoute =
  AuthenticatedAdminFundFundIdRouteImport.update({
    id: '/admin/fund/$fundId',
    path: '/admin/fund/$fundId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPacketFundIdRoute =
  AuthenticatedAdminPacketFundIdRouteImport.update({
    id: '/admin/packet/$fundId',
    path: '/admin/packet/$fundId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicEmailClickRoute = ApiPublicEmailClickRouteImport.update({
  id: '/api/public/email/click',
  path: '/api/public/email/click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailOpenRoute = ApiPublicEmailOpenRouteImport.update({
  id: '/api/public/email/open',
  path: '/api/public/email/open',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyDrainRoute = ApiPublicNotifyDrainRouteImport.update({
  id: '/api/public/notify/drain',
  path: '/api/public/notify/drain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPacketTokenRoute = ApiPublicPacketTokenRouteImport.update({
  id: '/api/public/packet/$token',
  path: '/api/public/packet/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksBoxSignRoute =
  ApiPublicWebhooksBoxSignRouteImport.update({
    id: '/api/public/webhooks/box-sign',
    path: '/api/public/webhooks/box-sign',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksDiditRoute = ApiPublicWebhooksDiditRouteImport.update({
  id: '/api/public/webhooks/didit',
  path: '/api/public/webhooks/didit',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/manager-login': typeof ManagerLoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/wire': typeof AuthenticatedWireRoute
  '/wire-confirmation': typeof AuthenticatedWireConfirmationRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/$applicationId': typeof AuthenticatedAdminApplicationIdRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/document-log': typeof AuthenticatedAdminDocumentLogRoute
  '/admin/email-preview': typeof AuthenticatedAdminEmailPreviewRoute
  '/admin/funding': typeof AuthenticatedAdminFundingRoute
  '/admin/funds': typeof AuthenticatedAdminFundsRoute
  '/admin/funnel': typeof AuthenticatedAdminFunnelRoute
  '/admin/new-application': typeof AuthenticatedAdminNewApplicationRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/admin/wire': typeof AuthenticatedAdminWireRoute
  '/diligence/$offeringId': typeof AuthenticatedDiligenceOfferingIdRoute
  '/manager/$applicationId': typeof AuthenticatedManagerApplicationIdRoute
  '/manager/activity': typeof AuthenticatedManagerActivityRoute
  '/manager/closing': typeof AuthenticatedManagerClosingRoute
  '/manager/diligence': typeof AuthenticatedManagerDiligenceRoute
  '/manager/documents': typeof AuthenticatedManagerDocumentsRoute
  '/manager/inbox': typeof AuthenticatedManagerInboxRoute
  '/manager/investors': typeof AuthenticatedManagerInvestorsRoute
  '/manager/onboarding': typeof AuthenticatedManagerOnboardingRoute
  '/manager/profile': typeof AuthenticatedManagerProfileRoute
  '/manager/timeline': typeof AuthenticatedManagerTimelineRoute
  '/manager/wires': typeof AuthenticatedManagerWiresRoute
  '/onboarding/accreditation': typeof AuthenticatedOnboardingAccreditationRoute
  '/onboarding/aml': typeof AuthenticatedOnboardingAmlRoute
  '/onboarding/documents': typeof AuthenticatedOnboardingDocumentsRoute
  '/onboarding/funding': typeof AuthenticatedOnboardingFundingRoute
  '/onboarding/kyc': typeof AuthenticatedOnboardingKycRoute
  '/api/public/login-attempt': typeof ApiPublicLoginAttemptRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/diligence/': typeof AuthenticatedDiligenceIndexRoute
  '/manager/': typeof AuthenticatedManagerIndexRoute
  '/admin/fund/$fundId': typeof AuthenticatedAdminFundFundIdRoute
  '/admin/packet/$fundId': typeof AuthenticatedAdminPacketFundIdRoute
  '/api/public/email/click': typeof ApiPublicEmailClickRoute
  '/api/public/email/open': typeof ApiPublicEmailOpenRoute
  '/api/public/notify/drain': typeof ApiPublicNotifyDrainRoute
  '/api/public/packet/$token': typeof ApiPublicPacketTokenRoute
  '/api/public/webhooks/box-sign': typeof ApiPublicWebhooksBoxSignRoute
  '/api/public/webhooks/didit': typeof ApiPublicWebhooksDiditRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manager-login': typeof ManagerLoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/wire': typeof AuthenticatedWireRoute
  '/wire-confirmation': typeof AuthenticatedWireConfirmationRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth': typeof AuthIndexRoute
  '/admin/$applicationId': typeof AuthenticatedAdminApplicationIdRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/document-log': typeof AuthenticatedAdminDocumentLogRoute
  '/admin/email-preview': typeof AuthenticatedAdminEmailPreviewRoute
  '/admin/funding': typeof AuthenticatedAdminFundingRoute
  '/admin/funds': typeof AuthenticatedAdminFundsRoute
  '/admin/funnel': typeof AuthenticatedAdminFunnelRoute
  '/admin/new-application': typeof AuthenticatedAdminNewApplicationRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/admin/wire': typeof AuthenticatedAdminWireRoute
  '/diligence/$offeringId': typeof AuthenticatedDiligenceOfferingIdRoute
  '/manager/$applicationId': typeof AuthenticatedManagerApplicationIdRoute
  '/manager/activity': typeof AuthenticatedManagerActivityRoute
  '/manager/closing': typeof AuthenticatedManagerClosingRoute
  '/manager/diligence': typeof AuthenticatedManagerDiligenceRoute
  '/manager/documents': typeof AuthenticatedManagerDocumentsRoute
  '/manager/inbox': typeof AuthenticatedManagerInboxRoute
  '/manager/investors': typeof AuthenticatedManagerInvestorsRoute
  '/manager/onboarding': typeof AuthenticatedManagerOnboardingRoute
  '/manager/profile': typeof AuthenticatedManagerProfileRoute
  '/manager/timeline': typeof AuthenticatedManagerTimelineRoute
  '/manager/wires': typeof AuthenticatedManagerWiresRoute
  '/onboarding/accreditation': typeof AuthenticatedOnboardingAccreditationRoute
  '/onboarding/aml': typeof AuthenticatedOnboardingAmlRoute
  '/onboarding/documents': typeof AuthenticatedOnboardingDocumentsRoute
  '/onboarding/funding': typeof AuthenticatedOnboardingFundingRoute
  '/onboarding/kyc': typeof AuthenticatedOnboardingKycRoute
  '/api/public/login-attempt': typeof ApiPublicLoginAttemptRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/diligence': typeof AuthenticatedDiligenceIndexRoute
  '/manager': typeof AuthenticatedManagerIndexRoute
  '/admin/fund/$fundId': typeof AuthenticatedAdminFundFundIdRoute
  '/admin/packet/$fundId': typeof AuthenticatedAdminPacketFundIdRoute
  '/api/public/email/click': typeof ApiPublicEmailClickRoute
  '/api/public/email/open': typeof ApiPublicEmailOpenRoute
  '/api/public/notify/drain': typeof ApiPublicNotifyDrainRoute
  '/api/public/packet/$token': typeof ApiPublicPacketTokenRoute
  '/api/public/webhooks/box-sign': typeof ApiPublicWebhooksBoxSignRoute
  '/api/public/webhooks/didit': typeof ApiPublicWebhooksDiditRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/manager-login': typeof ManagerLoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/wire': typeof AuthenticatedWireRoute
  '/_authenticated/wire-confirmation': typeof AuthenticatedWireConfirmationRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/admin/$applicationId': typeof AuthenticatedAdminApplicationIdRoute
  '/_authenticated/admin/access': typeof AuthenticatedAdminAccessRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/document-log': typeof AuthenticatedAdminDocumentLogRoute
  '/_authenticated/admin/email-preview': typeof AuthenticatedAdminEmailPreviewRoute
  '/_authenticated/admin/funding': typeof AuthenticatedAdminFundingRoute
  '/_authenticated/admin/funds': typeof AuthenticatedAdminFundsRoute
  '/_authenticated/admin/funnel': typeof AuthenticatedAdminFunnelRoute
  '/_authenticated/admin/new-application': typeof AuthenticatedAdminNewApplicationRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/_authenticated/admin/wire': typeof AuthenticatedAdminWireRoute
  '/_authenticated/diligence/$offeringId': typeof AuthenticatedDiligenceOfferingIdRoute
  '/_authenticated/manager/$applicationId': typeof AuthenticatedManagerApplicationIdRoute
  '/_authenticated/manager/activity': typeof AuthenticatedManagerActivityRoute
  '/_authenticated/manager/closing': typeof AuthenticatedManagerClosingRoute
  '/_authenticated/manager/diligence': typeof AuthenticatedManagerDiligenceRoute
  '/_authenticated/manager/documents': typeof AuthenticatedManagerDocumentsRoute
  '/_authenticated/manager/inbox': typeof AuthenticatedManagerInboxRoute
  '/_authenticated/manager/investors': typeof AuthenticatedManagerInvestorsRoute
  '/_authenticated/manager/onboarding': typeof AuthenticatedManagerOnboardingRoute
  '/_authenticated/manager/profile': typeof AuthenticatedManagerProfileRoute
  '/_authenticated/manager/timeline': typeof AuthenticatedManagerTimelineRoute
  '/_authenticated/manager/wires': typeof AuthenticatedManagerWiresRoute
  '/_authenticated/onboarding/accreditation': typeof AuthenticatedOnboardingAccreditationRoute
  '/_authenticated/onboarding/aml': typeof AuthenticatedOnboardingAmlRoute
  '/_authenticated/onboarding/documents': typeof AuthenticatedOnboardingDocumentsRoute
  '/_authenticated/onboarding/funding': typeof AuthenticatedOnboardingFundingRoute
  '/_authenticated/onboarding/kyc': typeof AuthenticatedOnboardingKycRoute
  '/api/public/login-attempt': typeof ApiPublicLoginAttemptRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/diligence/': typeof AuthenticatedDiligenceIndexRoute
  '/_authenticated/manager/': typeof AuthenticatedManagerIndexRoute
  '/_authenticated/admin/fund/$fundId': typeof AuthenticatedAdminFundFundIdRoute
  '/_authenticated/admin/packet/$fundId': typeof AuthenticatedAdminPacketFundIdRoute
  '/api/public/email/click': typeof ApiPublicEmailClickRoute
  '/api/public/email/open': typeof ApiPublicEmailOpenRoute
  '/api/public/notify/drain': typeof ApiPublicNotifyDrainRoute
  '/api/public/packet/$token': typeof ApiPublicPacketTokenRoute
  '/api/public/webhooks/box-sign': typeof ApiPublicWebhooksBoxSignRoute
  '/api/public/webhooks/didit': typeof ApiPublicWebhooksDiditRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/manager-login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard'
    | '/documents'
    | '/portal'
    | '/subscription'
    | '/wire'
    | '/wire-confirmation'
    | '/auth/forgot'
    | '/auth/register'
    | '/auth/'
    | '/admin/$applicationId'
    | '/admin/access'
    | '/admin/activity'
    | '/admin/document-log'
    | '/admin/email-preview'
    | '/admin/funding'
    | '/admin/funds'
    | '/admin/funnel'
    | '/admin/new-application'
    | '/admin/security'
    | '/admin/setup'
    | '/admin/wire'
    | '/diligence/$offeringId'
    | '/manager/$applicationId'
    | '/manager/activity'
    | '/manager/closing'
    | '/manager/diligence'
    | '/manager/documents'
    | '/manager/inbox'
    | '/manager/investors'
    | '/manager/onboarding'
    | '/manager/profile'
    | '/manager/timeline'
    | '/manager/wires'
    | '/onboarding/accreditation'
    | '/onboarding/aml'
    | '/onboarding/documents'
    | '/onboarding/funding'
    | '/onboarding/kyc'
    | '/api/public/login-attempt'
    | '/lovable/email/events'
    | '/admin/'
    | '/diligence/'
    | '/manager/'
    | '/admin/fund/$fundId'
    | '/admin/packet/$fundId'
    | '/api/public/email/click'
    | '/api/public/email/open'
    | '/api/public/notify/drain'
    | '/api/public/packet/$token'
    | '/api/public/webhooks/box-sign'
    | '/api/public/webhooks/didit'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manager-login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard'
    | '/documents'
    | '/portal'
    | '/subscription'
    | '/wire'
    | '/wire-confirmation'
    | '/auth/forgot'
    | '/auth/register'
    | '/auth'
    | '/admin/$applicationId'
    | '/admin/access'
    | '/admin/activity'
    | '/admin/document-log'
    | '/admin/email-preview'
    | '/admin/funding'
    | '/admin/funds'
    | '/admin/funnel'
    | '/admin/new-application'
    | '/admin/security'
    | '/admin/setup'
    | '/admin/wire'
    | '/diligence/$offeringId'
    | '/manager/$applicationId'
    | '/manager/activity'
    | '/manager/closing'
    | '/manager/diligence'
    | '/manager/documents'
    | '/manager/inbox'
    | '/manager/investors'
    | '/manager/onboarding'
    | '/manager/profile'
    | '/manager/timeline'
    | '/manager/wires'
    | '/onboarding/accreditation'
    | '/onboarding/aml'
    | '/onboarding/documents'
    | '/onboarding/funding'
    | '/onboarding/kyc'
    | '/api/public/login-attempt'
    | '/lovable/email/events'
    | '/admin'
    | '/diligence'
    | '/manager'
    | '/admin/fund/$fundId'
    | '/admin/packet/$fundId'
    | '/api/public/email/click'
    | '/api/public/email/open'
    | '/api/public/notify/drain'
    | '/api/public/packet/$token'
    | '/api/public/webhooks/box-sign'
    | '/api/public/webhooks/didit'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/manager-login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/portal'
    | '/_authenticated/subscription'
    | '/_authenticated/wire'
    | '/_authenticated/wire-confirmation'
    | '/auth/forgot'
    | '/auth/register'
    | '/auth/'
    | '/_authenticated/admin/$applicationId'
    | '/_authenticated/admin/access'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/document-log'
    | '/_authenticated/admin/email-preview'
    | '/_authenticated/admin/funding'
    | '/_authenticated/admin/funds'
    | '/_authenticated/admin/funnel'
    | '/_authenticated/admin/new-application'
    | '/_authenticated/admin/security'
    | '/_authenticated/admin/setup'
    | '/_authenticated/admin/wire'
    | '/_authenticated/diligence/$offeringId'
    | '/_authenticated/manager/$applicationId'
    | '/_authenticated/manager/activity'
    | '/_authenticated/manager/closing'
    | '/_authenticated/manager/diligence'
    | '/_authenticated/manager/documents'
    | '/_authenticated/manager/inbox'
    | '/_authenticated/manager/investors'
    | '/_authenticated/manager/onboarding'
    | '/_authenticated/manager/profile'
    | '/_authenticated/manager/timeline'
    | '/_authenticated/manager/wires'
    | '/_authenticated/onboarding/accreditation'
    | '/_authenticated/onboarding/aml'
    | '/_authenticated/onboarding/documents'
    | '/_authenticated/onboarding/funding'
    | '/_authenticated/onboarding/kyc'
    | '/api/public/login-attempt'
    | '/lovable/email/events'
    | '/_authenticated/admin/'
    | '/_authenticated/diligence/'
    | '/_authenticated/manager/'
    | '/_authenticated/admin/fund/$fundId'
    | '/_authenticated/admin/packet/$fundId'
    | '/api/public/email/click'
    | '/api/public/email/open'
    | '/api/public/notify/drain'
    | '/api/public/packet/$token'
    | '/api/public/webhooks/box-sign'
    | '/api/public/webhooks/didit'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ManagerLoginRoute: typeof ManagerLoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicLoginAttemptRoute: typeof ApiPublicLoginAttemptRoute
  LovableEmailEventsRoute: typeof LovableEmailEventsRoute
  ApiPublicEmailClickRoute: typeof ApiPublicEmailClickRoute
  ApiPublicEmailOpenRoute: typeof ApiPublicEmailOpenRoute
  ApiPublicNotifyDrainRoute: typeof ApiPublicNotifyDrainRoute
  ApiPublicPacketTokenRoute: typeof ApiPublicPacketTokenRoute
  ApiPublicWebhooksBoxSignRoute: typeof ApiPublicWebhooksBoxSignRoute
  ApiPublicWebhooksDiditRoute: typeof ApiPublicWebhooksDiditRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-login': {
      id: '/manager-login'
      path: '/manager-login'
      fullPath: '/manager-login'
      preLoaderRoute: typeof ManagerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wire': {
      id: '/_authenticated/wire'
      path: '/wire'
      fullPath: '/wire'
      preLoaderRoute: typeof AuthenticatedWireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wire-confirmation': {
      id: '/_authenticated/wire-confirmation'
      path: '/wire-confirmation'
      fullPath: '/wire-confirmation'
      preLoaderRoute: typeof AuthenticatedWireConfirmationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$applicationId': {
      id: '/_authenticated/admin/$applicationId'
      path: '/admin/$applicationId'
      fullPath: '/admin/$applicationId'
      preLoaderRoute: typeof AuthenticatedAdminApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/access': {
      id: '/_authenticated/admin/access'
      path: '/admin/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AuthenticatedAdminAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/document-log': {
      id: '/_authenticated/admin/document-log'
      path: '/admin/document-log'
      fullPath: '/admin/document-log'
      preLoaderRoute: typeof AuthenticatedAdminDocumentLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/email-preview': {
      id: '/_authenticated/admin/email-preview'
      path: '/admin/email-preview'
      fullPath: '/admin/email-preview'
      preLoaderRoute: typeof AuthenticatedAdminEmailPreviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/funding': {
      id: '/_authenticated/admin/funding'
      path: '/admin/funding'
      fullPath: '/admin/funding'
      preLoaderRoute: typeof AuthenticatedAdminFundingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/funds': {
      id: '/_authenticated/admin/funds'
      path: '/admin/funds'
      fullPath: '/admin/funds'
      preLoaderRoute: typeof AuthenticatedAdminFundsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/funnel': {
      id: '/_authenticated/admin/funnel'
      path: '/admin/funnel'
      fullPath: '/admin/funnel'
      preLoaderRoute: typeof AuthenticatedAdminFunnelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/new-application': {
      id: '/_authenticated/admin/new-application'
      path: '/admin/new-application'
      fullPath: '/admin/new-application'
      preLoaderRoute: typeof AuthenticatedAdminNewApplicationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/setup': {
      id: '/_authenticated/admin/setup'
      path: '/admin/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AuthenticatedAdminSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/wire': {
      id: '/_authenticated/admin/wire'
      path: '/admin/wire'
      fullPath: '/admin/wire'
      preLoaderRoute: typeof AuthenticatedAdminWireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diligence/': {
      id: '/_authenticated/diligence/'
      path: '/diligence'
      fullPath: '/diligence/'
      preLoaderRoute: typeof AuthenticatedDiligenceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diligence/$offeringId': {
      id: '/_authenticated/diligence/$offeringId'
      path: '/diligence/$offeringId'
      fullPath: '/diligence/$offeringId'
      preLoaderRoute: typeof AuthenticatedDiligenceOfferingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/': {
      id: '/_authenticated/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof AuthenticatedManagerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/$applicationId': {
      id: '/_authenticated/manager/$applicationId'
      path: '/manager/$applicationId'
      fullPath: '/manager/$applicationId'
      preLoaderRoute: typeof AuthenticatedManagerApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/activity': {
      id: '/_authenticated/manager/activity'
      path: '/manager/activity'
      fullPath: '/manager/activity'
      preLoaderRoute: typeof AuthenticatedManagerActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/closing': {
      id: '/_authenticated/manager/closing'
      path: '/manager/closing'
      fullPath: '/manager/closing'
      preLoaderRoute: typeof AuthenticatedManagerClosingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/diligence': {
      id: '/_authenticated/manager/diligence'
      path: '/manager/diligence'
      fullPath: '/manager/diligence'
      preLoaderRoute: typeof AuthenticatedManagerDiligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/documents': {
      id: '/_authenticated/manager/documents'
      path: '/manager/documents'
      fullPath: '/manager/documents'
      preLoaderRoute: typeof AuthenticatedManagerDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/inbox': {
      id: '/_authenticated/manager/inbox'
      path: '/manager/inbox'
      fullPath: '/manager/inbox'
      preLoaderRoute: typeof AuthenticatedManagerInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/investors': {
      id: '/_authenticated/manager/investors'
      path: '/manager/investors'
      fullPath: '/manager/investors'
      preLoaderRoute: typeof AuthenticatedManagerInvestorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/onboarding': {
      id: '/_authenticated/manager/onboarding'
      path: '/manager/onboarding'
      fullPath: '/manager/onboarding'
      preLoaderRoute: typeof AuthenticatedManagerOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/profile': {
      id: '/_authenticated/manager/profile'
      path: '/manager/profile'
      fullPath: '/manager/profile'
      preLoaderRoute: typeof AuthenticatedManagerProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/timeline': {
      id: '/_authenticated/manager/timeline'
      path: '/manager/timeline'
      fullPath: '/manager/timeline'
      preLoaderRoute: typeof AuthenticatedManagerTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/wires': {
      id: '/_authenticated/manager/wires'
      path: '/manager/wires'
      fullPath: '/manager/wires'
      preLoaderRoute: typeof AuthenticatedManagerWiresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/accreditation': {
      id: '/_authenticated/onboarding/accreditation'
      path: '/onboarding/accreditation'
      fullPath: '/onboarding/accreditation'
      preLoaderRoute: typeof AuthenticatedOnboardingAccreditationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/aml': {
      id: '/_authenticated/onboarding/aml'
      path: '/onboarding/aml'
      fullPath: '/onboarding/aml'
      preLoaderRoute: typeof AuthenticatedOnboardingAmlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/documents': {
      id: '/_authenticated/onboarding/documents'
      path: '/onboarding/documents'
      fullPath: '/onboarding/documents'
      preLoaderRoute: typeof AuthenticatedOnboardingDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/funding': {
      id: '/_authenticated/onboarding/funding'
      path: '/onboarding/funding'
      fullPath: '/onboarding/funding'
      preLoaderRoute: typeof AuthenticatedOnboardingFundingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/kyc': {
      id: '/_authenticated/onboarding/kyc'
      path: '/onboarding/kyc'
      fullPath: '/onboarding/kyc'
      preLoaderRoute: typeof AuthenticatedOnboardingKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/login-attempt': {
      id: '/api/public/login-attempt'
      path: '/api/public/login-attempt'
      fullPath: '/api/public/login-attempt'
      preLoaderRoute: typeof ApiPublicLoginAttemptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/events': {
      id: '/lovable/email/events'
      path: '/lovable/email/events'
      fullPath: '/lovable/email/events'
      preLoaderRoute: typeof LovableEmailEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/fund/$fundId': {
      id: '/_authenticated/admin/fund/$fundId'
      path: '/admin/fund/$fundId'
      fullPath: '/admin/fund/$fundId'
      preLoaderRoute: typeof AuthenticatedAdminFundFundIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/packet/$fundId': {
      id: '/_authenticated/admin/packet/$fundId'
      path: '/admin/packet/$fundId'
      fullPath: '/admin/packet/$fundId'
      preLoaderRoute: typeof AuthenticatedAdminPacketFundIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/email/click': {
      id: '/api/public/email/click'
      path: '/api/public/email/click'
      fullPath: '/api/public/email/click'
      preLoaderRoute: typeof ApiPublicEmailClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email/open': {
      id: '/api/public/email/open'
      path: '/api/public/email/open'
      fullPath: '/api/public/email/open'
      preLoaderRoute: typeof ApiPublicEmailOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify/drain': {
      id: '/api/public/notify/drain'
      path: '/api/public/notify/drain'
      fullPath: '/api/public/notify/drain'
      preLoaderRoute: typeof ApiPublicNotifyDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/packet/$token': {
      id: '/api/public/packet/$token'
      path: '/api/public/packet/$token'
      fullPath: '/api/public/packet/$token'
      preLoaderRoute: typeof ApiPublicPacketTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/box-sign': {
      id: '/api/public/webhooks/box-sign'
      path: '/api/public/webhooks/box-sign'
      fullPath: '/api/public/webhooks/box-sign'
      preLoaderRoute: typeof ApiPublicWebhooksBoxSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/didit': {
      id: '/api/public/webhooks/didit'
      path: '/api/public/webhooks/didit'
      fullPath: '/api/public/webhooks/didit'
      preLoaderRoute: typeof ApiPublicWebhooksDiditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedWireRoute: typeof AuthenticatedWireRoute
  AuthenticatedWireConfirmationRoute: typeof AuthenticatedWireConfirmationRoute
  AuthenticatedAdminApplicationIdRoute: typeof AuthenticatedAdminApplicationIdRoute
  AuthenticatedAdminAccessRoute: typeof AuthenticatedAdminAccessRoute
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminDocumentLogRoute: typeof AuthenticatedAdminDocumentLogRoute
  AuthenticatedAdminEmailPreviewRoute: typeof AuthenticatedAdminEmailPreviewRoute
  AuthenticatedAdminFundingRoute: typeof AuthenticatedAdminFundingRoute
  AuthenticatedAdminFundsRoute: typeof AuthenticatedAdminFundsRoute
  AuthenticatedAdminFunnelRoute: typeof AuthenticatedAdminFunnelRoute
  AuthenticatedAdminNewApplicationRoute: typeof AuthenticatedAdminNewApplicationRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminSetupRoute: typeof AuthenticatedAdminSetupRoute
  AuthenticatedAdminWireRoute: typeof AuthenticatedAdminWireRoute
  AuthenticatedDiligenceOfferingIdRoute: typeof AuthenticatedDiligenceOfferingIdRoute
  AuthenticatedManagerApplicationIdRoute: typeof AuthenticatedManagerApplicationIdRoute
  AuthenticatedManagerActivityRoute: typeof AuthenticatedManagerActivityRoute
  AuthenticatedManagerClosingRoute: typeof AuthenticatedManagerClosingRoute
  AuthenticatedManagerDiligenceRoute: typeof AuthenticatedManagerDiligenceRoute
  AuthenticatedManagerDocumentsRoute: typeof AuthenticatedManagerDocumentsRoute
  AuthenticatedManagerInboxRoute: typeof AuthenticatedManagerInboxRoute
  AuthenticatedManagerInvestorsRoute: typeof AuthenticatedManagerInvestorsRoute
  AuthenticatedManagerOnboardingRoute: typeof AuthenticatedManagerOnboardingRoute
  AuthenticatedManagerProfileRoute: typeof AuthenticatedManagerProfileRoute
  AuthenticatedManagerTimelineRoute: typeof AuthenticatedManagerTimelineRoute
  AuthenticatedManagerWiresRoute: typeof AuthenticatedManagerWiresRoute
  AuthenticatedOnboardingAccreditationRoute: typeof AuthenticatedOnboardingAccreditationRoute
  AuthenticatedOnboardingAmlRoute: typeof AuthenticatedOnboardingAmlRoute
  AuthenticatedOnboardingDocumentsRoute: typeof AuthenticatedOnboardingDocumentsRoute
  AuthenticatedOnboardingFundingRoute: typeof AuthenticatedOnboardingFundingRoute
  AuthenticatedOnboardingKycRoute: typeof AuthenticatedOnboardingKycRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedDiligenceIndexRoute: typeof AuthenticatedDiligenceIndexRoute
  AuthenticatedManagerIndexRoute: typeof AuthenticatedManagerIndexRoute
  AuthenticatedAdminFundFundIdRoute: typeof AuthenticatedAdminFundFundIdRoute
  AuthenticatedAdminPacketFundIdRoute: typeof AuthenticatedAdminPacketFundIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedWireRoute: AuthenticatedWireRoute,
  AuthenticatedWireConfirmationRoute: AuthenticatedWireConfirmationRoute,
  AuthenticatedAdminApplicationIdRoute: AuthenticatedAdminApplicationIdRoute,
  AuthenticatedAdminAccessRoute: AuthenticatedAdminAccessRoute,
  AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
  AuthenticatedAdminDocumentLogRoute: AuthenticatedAdminDocumentLogRoute,
  AuthenticatedAdminEmailPreviewRoute: AuthenticatedAdminEmailPreviewRoute,
  AuthenticatedAdminFundingRoute: AuthenticatedAdminFundingRoute,
  AuthenticatedAdminFundsRoute: AuthenticatedAdminFundsRoute,
  AuthenticatedAdminFunnelRoute: AuthenticatedAdminFunnelRoute,
  AuthenticatedAdminNewApplicationRoute: AuthenticatedAdminNewApplicationRoute,
  AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
  AuthenticatedAdminSetupRoute: AuthenticatedAdminSetupRoute,
  AuthenticatedAdminWireRoute: AuthenticatedAdminWireRoute,
  AuthenticatedDiligenceOfferingIdRoute: AuthenticatedDiligenceOfferingIdRoute,
  AuthenticatedManagerApplicationIdRoute:
    AuthenticatedManagerApplicationIdRoute,
  AuthenticatedManagerActivityRoute: AuthenticatedManagerActivityRoute,
  AuthenticatedManagerClosingRoute: AuthenticatedManagerClosingRoute,
  AuthenticatedManagerDiligenceRoute: AuthenticatedManagerDiligenceRoute,
  AuthenticatedManagerDocumentsRoute: AuthenticatedManagerDocumentsRoute,
  AuthenticatedManagerInboxRoute: AuthenticatedManagerInboxRoute,
  AuthenticatedManagerInvestorsRoute: AuthenticatedManagerInvestorsRoute,
  AuthenticatedManagerOnboardingRoute: AuthenticatedManagerOnboardingRoute,
  AuthenticatedManagerProfileRoute: AuthenticatedManagerProfileRoute,
  AuthenticatedManagerTimelineRoute: AuthenticatedManagerTimelineRoute,
  AuthenticatedManagerWiresRoute: AuthenticatedManagerWiresRoute,
  AuthenticatedOnboardingAccreditationRoute:
    AuthenticatedOnboardingAccreditationRoute,
  AuthenticatedOnboardingAmlRoute: AuthenticatedOnboardingAmlRoute,
  AuthenticatedOnboardingDocumentsRoute: AuthenticatedOnboardingDocumentsRoute,
  AuthenticatedOnboardingFundingRoute: AuthenticatedOnboardingFundingRoute,
  AuthenticatedOnboardingKycRoute: AuthenticatedOnboardingKycRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedDiligenceIndexRoute: AuthenticatedDiligenceIndexRoute,
  AuthenticatedManagerIndexRoute: AuthenticatedManagerIndexRoute,
  AuthenticatedAdminFundFundIdRoute: AuthenticatedAdminFundFundIdRoute,
  AuthenticatedAdminPacketFundIdRoute: AuthenticatedAdminPacketFundIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ManagerLoginRoute: ManagerLoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicLoginAttemptRoute: ApiPublicLoginAttemptRoute,
  LovableEmailEventsRoute: LovableEmailEventsRoute,
  ApiPublicEmailClickRoute: ApiPublicEmailClickRoute,
  ApiPublicEmailOpenRoute: ApiPublicEmailOpenRoute,
  ApiPublicNotifyDrainRoute: ApiPublicNotifyDrainRoute,
  ApiPublicPacketTokenRoute: ApiPublicPacketTokenRoute,
  ApiPublicWebhooksBoxSignRoute: ApiPublicWebhooksBoxSignRoute,
  ApiPublicWebhooksDiditRoute: ApiPublicWebhooksDiditRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
