/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FundAdministrationRouteImport } from './routes/fund-administration'
import { Route as ManagerLoginRouteImport } from './routes/manager-login'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SpvRouteImport } from './routes/spv'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedApplyRouteImport } from './routes/_authenticated/apply'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedFundDocumentsRouteImport } from './routes/_authenticated/fund-documents'
import { Route as AuthenticatedFundMemoRouteImport } from './routes/_authenticated/fund-memo'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedMyPortfolioRouteImport } from './routes/_authenticated/my-portfolio'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedWireRouteImport } from './routes/_authenticated/wire'
import { Route as AuthenticatedWireConfirmationRouteImport } from './routes/_authenticated/wire-confirmation'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as FundSlugRouteImport } from './routes/fund.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminApplicationIdRouteImport } from './routes/_authenticated/admin.$applicationId'
import { Route as AuthenticatedAdminAccessRouteImport } from './routes/_authenticated/admin.access'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin.activity'
import { Route as AuthenticatedAdminCapTableRouteImport } from './routes/_authenticated/admin.cap-table'
import { Route as AuthenticatedAdminCapTableBoardRouteImport } from './routes/_authenticated/admin.cap-table-board'
import { Route as AuthenticatedAdminDocumentLogRouteImport } from './routes/_authenticated/admin.document-log'
import { Route as AuthenticatedAdminEmailPreviewRouteImport } from './routes/_authenticated/admin.email-preview'
import { Route as AuthenticatedAdminFundingRouteImport } from './routes/_authenticated/admin.funding'
import { Route as AuthenticatedAdminFundsRouteImport } from './routes/_authenticated/admin.funds'
import { Route as AuthenticatedAdminFunnelRouteImport } from './routes/_authenticated/admin.funnel'
import { Route as AuthenticatedAdminInvestorsRouteImport } from './routes/_authenticated/admin.investors'
import { Route as AuthenticatedAdminMemoRouteImport } from './routes/_authenticated/admin.memo'
import { Route as AuthenticatedAdminNewApplicationRouteImport } from './routes/_authenticated/admin.new-application'
import { Route as AuthenticatedAdminOfferingStatementRouteImport } from './routes/_authenticated/admin.offering-statement'
import { Route as AuthenticatedAdminPerformanceRouteImport } from './routes/_authenticated/admin.performance'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin.permissions'
import { Route as AuthenticatedAdminPortfolioValueRouteImport } from './routes/_authenticated/admin.portfolio-value'
import { Route as AuthenticatedAdminRequestsRouteImport } from './routes/_authenticated/admin.requests'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin.security'
import { Route as AuthenticatedAdminSetupRouteImport } from './routes/_authenticated/admin.setup'
import { Route as AuthenticatedAdminTimelineRouteImport } from './routes/_authenticated/admin.timeline'
import { Route as AuthenticatedAdminWireRouteImport } from './routes/_authenticated/admin.wire'
import { Route as AuthenticatedDiligenceIndexRouteImport } from './routes/_authenticated/diligence.index'
import { Route as AuthenticatedDiligenceOfferingIdRouteImport } from './routes/_authenticated/diligence.$offeringId'
import { Route as AuthenticatedManagerIndexRouteImport } from './routes/_authenticated/manager.index'
import { Route as AuthenticatedManagerApplicationIdRouteImport } from './routes/_authenticated/manager.$applicationId'
import { Route as AuthenticatedManagerActivityRouteImport } from './routes/_authenticated/manager.activity'
import { Route as AuthenticatedManagerApprovalsRouteImport } from './routes/_authenticated/manager.approvals'
import { Route as AuthenticatedManagerCapTableRouteImport } from './routes/_authenticated/manager.cap-table'
import { Route as AuthenticatedManagerCapTableBoardRouteImport } from './routes/_authenticated/manager.cap-table-board'
import { Route as AuthenticatedManagerClosingRouteImport } from './routes/_authenticated/manager.closing'
import { Route as AuthenticatedManagerDiligenceRouteImport } from './routes/_authenticated/manager.diligence'
import { Route as AuthenticatedManagerDocumentsRouteImport } from './routes/_authenticated/manager.documents'
import { Route as AuthenticatedManagerInboxRouteImport } from './routes/_authenticated/manager.inbox'
import { Route as AuthenticatedManagerInvestorsRouteImport } from './routes/_authenticated/manager.investors'
import { Route as AuthenticatedManagerMemoRouteImport } from './routes/_authenticated/manager.memo'
import { Route as AuthenticatedManagerMessagesRouteImport } from './routes/_authenticated/manager.messages'
import { Route as AuthenticatedManagerOfferingStatementRouteImport } from './routes/_authenticated/manager.offering-statement'
import { Route as AuthenticatedManagerOnboardingRouteImport } from './routes/_authenticated/manager.onboarding'
import { Route as AuthenticatedManagerPerformanceRouteImport } from './routes/_authenticated/manager.performance'
import { Route as AuthenticatedManagerPermissionsRouteImport } from './routes/_authenticated/manager.permissions'
import { Route as AuthenticatedManagerPortfolioValueRouteImport } from './routes/_authenticated/manager.portfolio-value'
import { Route as AuthenticatedManagerProfileRouteImport } from './routes/_authenticated/manager.profile'
import { Route as AuthenticatedManagerPublicPageRouteImport } from './routes/_authenticated/manager.public-page'
import { Route as AuthenticatedManagerRequestsRouteImport } from './routes/_authenticated/manager.requests'
import { Route as AuthenticatedManagerTaxRouteImport } from './routes/_authenticated/manager.tax'
import { Route as AuthenticatedManagerTimelineRouteImport } from './routes/_authenticated/manager.timeline'
import { Route as AuthenticatedManagerWiresRouteImport } from './routes/_authenticated/manager.wires'
import { Route as AuthenticatedOnboardingAccreditationRouteImport } from './routes/_authenticated/onboarding.accreditation'
import { Route as AuthenticatedOnboardingAmlRouteImport } from './routes/_authenticated/onboarding.aml'
import { Route as AuthenticatedOnboardingDocumentsRouteImport } from './routes/_authenticated/onboarding.documents'
import { Route as AuthenticatedOnboardingFundingRouteImport } from './routes/_authenticated/onboarding.funding'
import { Route as AuthenticatedOnboardingKycRouteImport } from './routes/_authenticated/onboarding.kyc'
import { Route as AuthenticatedOpsIndexRouteImport } from './routes/_authenticated/ops.index'
import { Route as AuthenticatedOpsBankingRouteImport } from './routes/_authenticated/ops.banking'
import { Route as AuthenticatedOpsSs4RouteImport } from './routes/_authenticated/ops.ss4'
import { Route as AuthenticatedOpsTaxDocumentsRouteImport } from './routes/_authenticated/ops.tax-documents'
import { Route as AuthenticatedOpsTeamRouteImport } from './routes/_authenticated/ops.team'
import { Route as ApiPublicLoginAttemptRouteImport } from './routes/api/public/login-attempt'
import { Route as LovableEmailEventsRouteImport } from './routes/lovable/email/events'
import { Route as AuthenticatedAdminContractsIndexRouteImport } from './routes/_authenticated/admin.contracts.index'
import { Route as AuthenticatedAdminContractsClientIdRouteImport } from './routes/_authenticated/admin.contracts.$clientId'
import { Route as AuthenticatedAdminFundFundIdRouteImport } from './routes/_authenticated/admin.fund.$fundId'
import { Route as AuthenticatedAdminPacketFundIdRouteImport } from './routes/_authenticated/admin.packet.$fundId'
import { Route as AuthenticatedManagerFundFundIdRouteImport } from './routes/_authenticated/manager.fund.$fundId'
import { Route as AuthenticatedOpsFundsFundIdRouteImport } from './routes/_authenticated/ops.funds.$fundId'
import { Route as ApiPublicEmailClickRouteImport } from './routes/api/public/email/click'
import { Route as ApiPublicEmailOpenRouteImport } from './routes/api/public/email/open'
import { Route as ApiPublicNotifyDrainRouteImport } from './routes/api/public/notify/drain'
import { Route as ApiPublicPacketTokenRouteImport } from './routes/api/public/packet/$token'
import { Route as ApiPublicWebhooksBoxSignRouteImport } from './routes/api/public/webhooks/box-sign'
import { Route as ApiPublicWebhooksDiditRouteImport } from './routes/api/public/webhooks/didit'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FundAdministrationRoute = FundAdministrationRouteImport.update({
  id: '/fund-administration',
  path: '/fund-administration',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerLoginRoute = ManagerLoginRouteImport.update({
  id: '/manager-login',
  path: '/manager-login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SpvRoute = SpvRouteImport.update({
  id: '/spv',
  path: '/spv',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplyRoute = AuthenticatedApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFundDocumentsRoute =
  AuthenticatedFundDocumentsRouteImport.update({
    id: '/fund-documents',
    path: '/fund-documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFundMemoRoute = AuthenticatedFundMemoRouteImport.update({
  id: '/fund-memo',
  path: '/fund-memo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyPortfolioRoute =
  AuthenticatedMyPortfolioRouteImport.update({
    id: '/my-portfolio',
    path: '/my-portfolio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWireRoute = AuthenticatedWireRouteImport.update({
  id: '/wire',
  path: '/wire',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWireConfirmationRoute =
  AuthenticatedWireConfirmationRouteImport.update({
    id: '/wire-confirmation',
    path: '/wire-confirmation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const FundSlugRoute = FundSlugRouteImport.update({
  id: '/fund/$slug',
  path: '/fund/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminApplicationIdRoute =
  AuthenticatedAdminApplicationIdRouteImport.update({
    id: '/admin/$applicationId',
    path: '/admin/$applicationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAccessRoute =
  AuthenticatedAdminAccessRouteImport.update({
    id: '/admin/access',
    path: '/admin/access',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/admin/activity',
    path: '/admin/activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCapTableRoute =
  AuthenticatedAdminCapTableRouteImport.update({
    id: '/admin/cap-table',
    path: '/admin/cap-table',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCapTableBoardRoute =
  AuthenticatedAdminCapTableBoardRouteImport.update({
    id: '/admin/cap-table-board',
    path: '/admin/cap-table-board',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDocumentLogRoute =
  AuthenticatedAdminDocumentLogRouteImport.update({
    id: '/admin/document-log',
    path: '/admin/document-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmailPreviewRoute =
  AuthenticatedAdminEmailPreviewRouteImport.update({
    id: '/admin/email-preview',
    path: '/admin/email-preview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFundingRoute =
  AuthenticatedAdminFundingRouteImport.update({
    id: '/admin/funding',
    path: '/admin/funding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFundsRoute = AuthenticatedAdminFundsRouteImport.update({
  id: '/admin/funds',
  path: '/admin/funds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminFunnelRoute =
  AuthenticatedAdminFunnelRouteImport.update({
    id: '/admin/funnel',
    path: '/admin/funnel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInvestorsRoute =
  AuthenticatedAdminInvestorsRouteImport.update({
    id: '/admin/investors',
    path: '/admin/investors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMemoRoute = AuthenticatedAdminMemoRouteImport.update({
  id: '/admin/memo',
  path: '/admin/memo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminNewApplicationRoute =
  AuthenticatedAdminNewApplicationRouteImport.update({
    id: '/admin/new-application',
    path: '/admin/new-application',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOfferingStatementRoute =
  AuthenticatedAdminOfferingStatementRouteImport.update({
    id: '/admin/offering-statement',
    path: '/admin/offering-statement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPerformanceRoute =
  AuthenticatedAdminPerformanceRouteImport.update({
    id: '/admin/performance',
    path: '/admin/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/admin/permissions',
    path: '/admin/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPortfolioValueRoute =
  AuthenticatedAdminPortfolioValueRouteImport.update({
    id: '/admin/portfolio-value',
    path: '/admin/portfolio-value',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRequestsRoute =
  AuthenticatedAdminRequestsRouteImport.update({
    id: '/admin/requests',
    path: '/admin/requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/admin/security',
    path: '/admin/security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSetupRoute = AuthenticatedAdminSetupRouteImport.update({
  id: '/admin/setup',
  path: '/admin/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTimelineRoute =
  AuthenticatedAdminTimelineRouteImport.update({
    id: '/admin/timeline',
    path: '/admin/timeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminWireRoute = AuthenticatedAdminWireRouteImport.update({
  id: '/admin/wire',
  path: '/admin/wire',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiligenceIndexRoute =
  AuthenticatedDiligenceIndexRouteImport.update({
    id: '/diligence/',
    path: '/diligence/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiligenceOfferingIdRoute =
  AuthenticatedDiligenceOfferingIdRouteImport.update({
    id: '/diligence/$offeringId',
    path: '/diligence/$offeringId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerIndexRoute =
  AuthenticatedManagerIndexRouteImport.update({
    id: '/manager/',
    path: '/manager/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerApplicationIdRoute =
  AuthenticatedManagerApplicationIdRouteImport.update({
    id: '/manager/$applicationId',
    path: '/manager/$applicationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerActivityRoute =
  AuthenticatedManagerActivityRouteImport.update({
    id: '/manager/activity',
    path: '/manager/activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerApprovalsRoute =
  AuthenticatedManagerApprovalsRouteImport.update({
    id: '/manager/approvals',
    path: '/manager/approvals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerCapTableRoute =
  AuthenticatedManagerCapTableRouteImport.update({
    id: '/manager/cap-table',
    path: '/manager/cap-table',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerCapTableBoardRoute =
  AuthenticatedManagerCapTableBoardRouteImport.update({
    id: '/manager/cap-table-board',
    path: '/manager/cap-table-board',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerClosingRoute =
  AuthenticatedManagerClosingRouteImport.update({
    id: '/manager/closing',
    path: '/manager/closing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerDiligenceRoute =
  AuthenticatedManagerDiligenceRouteImport.update({
    id: '/manager/diligence',
    path: '/manager/diligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerDocumentsRoute =
  AuthenticatedManagerDocumentsRouteImport.update({
    id: '/manager/documents',
    path: '/manager/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerInboxRoute =
  AuthenticatedManagerInboxRouteImport.update({
    id: '/manager/inbox',
    path: '/manager/inbox',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerInvestorsRoute =
  AuthenticatedManagerInvestorsRouteImport.update({
    id: '/manager/investors',
    path: '/manager/investors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerMemoRoute =
  AuthenticatedManagerMemoRouteImport.update({
    id: '/manager/memo',
    path: '/manager/memo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerMessagesRoute =
  AuthenticatedManagerMessagesRouteImport.update({
    id: '/manager/messages',
    path: '/manager/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerOfferingStatementRoute =
  AuthenticatedManagerOfferingStatementRouteImport.update({
    id: '/manager/offering-statement',
    path: '/manager/offering-statement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerOnboardingRoute =
  AuthenticatedManagerOnboardingRouteImport.update({
    id: '/manager/onboarding',
    path: '/manager/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerPerformanceRoute =
  AuthenticatedManagerPerformanceRouteImport.update({
    id: '/manager/performance',
    path: '/manager/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerPermissionsRoute =
  AuthenticatedManagerPermissionsRouteImport.update({
    id: '/manager/permissions',
    path: '/manager/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerPortfolioValueRoute =
  AuthenticatedManagerPortfolioValueRouteImport.update({
    id: '/manager/portfolio-value',
    path: '/manager/portfolio-value',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerProfileRoute =
  AuthenticatedManagerProfileRouteImport.update({
    id: '/manager/profile',
    path: '/manager/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerPublicPageRoute =
  AuthenticatedManagerPublicPageRouteImport.update({
    id: '/manager/public-page',
    path: '/manager/public-page',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerRequestsRoute =
  AuthenticatedManagerRequestsRouteImport.update({
    id: '/manager/requests',
    path: '/manager/requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerTaxRoute = AuthenticatedManagerTaxRouteImport.update({
  id: '/manager/tax',
  path: '/manager/tax',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManagerTimelineRoute =
  AuthenticatedManagerTimelineRouteImport.update({
    id: '/manager/timeline',
    path: '/manager/timeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerWiresRoute =
  AuthenticatedManagerWiresRouteImport.update({
    id: '/manager/wires',
    path: '/manager/wires',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingAccreditationRoute =
  AuthenticatedOnboardingAccreditationRouteImport.update({
    id: '/onboarding/accreditation',
    path: '/onboarding/accreditation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingAmlRoute =
  AuthenticatedOnboardingAmlRouteImport.update({
    id: '/onboarding/aml',
    path: '/onboarding/aml',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingDocumentsRoute =
  AuthenticatedOnboardingDocumentsRouteImport.update({
    id: '/onboarding/documents',
    path: '/onboarding/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingFundingRoute =
  AuthenticatedOnboardingFundingRouteImport.update({
    id: '/onboarding/funding',
    path: '/onboarding/funding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingKycRoute =
  AuthenticatedOnboardingKycRouteImport.update({
    id: '/onboarding/kyc',
    path: '/onboarding/kyc',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpsIndexRoute = AuthenticatedOpsIndexRouteImport.update({
  id: '/ops/',
  path: '/ops/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpsBankingRoute = AuthenticatedOpsBankingRouteImport.update({
  id: '/ops/banking',
  path: '/ops/banking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpsSs4Route = AuthenticatedOpsSs4RouteImport.update({
  id: '/ops/ss4',
  path: '/ops/ss4',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpsTaxDocumentsRoute =
  AuthenticatedOpsTaxDocumentsRouteImport.update({
    id: '/ops/tax-documents',
    path: '/ops/tax-documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpsTeamRoute = AuthenticatedOpsTeamRouteImport.update({
  id: '/ops/team',
  path: '/ops/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicLoginAttemptRoute = ApiPublicLoginAttemptRouteImport.update({
  id: '/api/public/login-attempt',
  path: '/api/public/login-attempt',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailEventsRoute = LovableEmailEventsRouteImport.update({
  id: '/lovable/email/events',
  path: '/lovable/email/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminContractsIndexRoute =
  AuthenticatedAdminContractsIndexRouteImport.update({
    id: '/admin/contracts/',
    path: '/admin/contracts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminContractsClientIdRoute =
  AuthenticatedAdminContractsClientIdRouteImport.update({
    id: '/admin/contracts/$clientId',
    path: '/admin/contracts/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFundFundIdRoute =
  AuthenticatedAdminFundFundIdRouteImport.update({
    id: '/admin/fund/$fundId',
    path: '/admin/fund/$fundId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPacketFundIdRoute =
  AuthenticatedAdminPacketFundIdRouteImport.update({
    id: '/admin/packet/$fundId',
    path: '/admin/packet/$fundId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerFundFundIdRoute =
  AuthenticatedManagerFundFundIdRouteImport.update({
    id: '/manager/fund/$fundId',
    path: '/manager/fund/$fundId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpsFundsFundIdRoute =
  AuthenticatedOpsFundsFundIdRouteImport.update({
    id: '/ops/funds/$fundId',
    path: '/ops/funds/$fundId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicEmailClickRoute = ApiPublicEmailClickRouteImport.update({
  id: '/api/public/email/click',
  path: '/api/public/email/click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailOpenRoute = ApiPublicEmailOpenRouteImport.update({
  id: '/api/public/email/open',
  path: '/api/public/email/open',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyDrainRoute = ApiPublicNotifyDrainRouteImport.update({
  id: '/api/public/notify/drain',
  path: '/api/public/notify/drain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPacketTokenRoute = ApiPublicPacketTokenRouteImport.update({
  id: '/api/public/packet/$token',
  path: '/api/public/packet/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksBoxSignRoute =
  ApiPublicWebhooksBoxSignRouteImport.update({
    id: '/api/public/webhooks/box-sign',
    path: '/api/public/webhooks/box-sign',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksDiditRoute = ApiPublicWebhooksDiditRouteImport.update({
  id: '/api/public/webhooks/didit',
  path: '/api/public/webhooks/didit',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/fund-administration': typeof FundAdministrationRoute
  '/manager-login': typeof ManagerLoginRoute
  '/platform': typeof PlatformRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spv': typeof SpvRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/apply': typeof AuthenticatedApplyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/fund-documents': typeof AuthenticatedFundDocumentsRoute
  '/fund-memo': typeof AuthenticatedFundMemoRoute
  '/home': typeof AuthenticatedHomeRoute
  '/my-portfolio': typeof AuthenticatedMyPortfolioRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/wire': typeof AuthenticatedWireRoute
  '/wire-confirmation': typeof AuthenticatedWireConfirmationRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/register': typeof AuthRegisterRoute
  '/fund/$slug': typeof FundSlugRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/$applicationId': typeof AuthenticatedAdminApplicationIdRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/cap-table': typeof AuthenticatedAdminCapTableRoute
  '/admin/cap-table-board': typeof AuthenticatedAdminCapTableBoardRoute
  '/admin/document-log': typeof AuthenticatedAdminDocumentLogRoute
  '/admin/email-preview': typeof AuthenticatedAdminEmailPreviewRoute
  '/admin/funding': typeof AuthenticatedAdminFundingRoute
  '/admin/funds': typeof AuthenticatedAdminFundsRoute
  '/admin/funnel': typeof AuthenticatedAdminFunnelRoute
  '/admin/investors': typeof AuthenticatedAdminInvestorsRoute
  '/admin/memo': typeof AuthenticatedAdminMemoRoute
  '/admin/new-application': typeof AuthenticatedAdminNewApplicationRoute
  '/admin/offering-statement': typeof AuthenticatedAdminOfferingStatementRoute
  '/admin/performance': typeof AuthenticatedAdminPerformanceRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/portfolio-value': typeof AuthenticatedAdminPortfolioValueRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/admin/timeline': typeof AuthenticatedAdminTimelineRoute
  '/admin/wire': typeof AuthenticatedAdminWireRoute
  '/diligence/$offeringId': typeof AuthenticatedDiligenceOfferingIdRoute
  '/manager/$applicationId': typeof AuthenticatedManagerApplicationIdRoute
  '/manager/activity': typeof AuthenticatedManagerActivityRoute
  '/manager/approvals': typeof AuthenticatedManagerApprovalsRoute
  '/manager/cap-table': typeof AuthenticatedManagerCapTableRoute
  '/manager/cap-table-board': typeof AuthenticatedManagerCapTableBoardRoute
  '/manager/closing': typeof AuthenticatedManagerClosingRoute
  '/manager/diligence': typeof AuthenticatedManagerDiligenceRoute
  '/manager/documents': typeof AuthenticatedManagerDocumentsRoute
  '/manager/inbox': typeof AuthenticatedManagerInboxRoute
  '/manager/investors': typeof AuthenticatedManagerInvestorsRoute
  '/manager/memo': typeof AuthenticatedManagerMemoRoute
  '/manager/messages': typeof AuthenticatedManagerMessagesRoute
  '/manager/offering-statement': typeof AuthenticatedManagerOfferingStatementRoute
  '/manager/onboarding': typeof AuthenticatedManagerOnboardingRoute
  '/manager/performance': typeof AuthenticatedManagerPerformanceRoute
  '/manager/permissions': typeof AuthenticatedManagerPermissionsRoute
  '/manager/portfolio-value': typeof AuthenticatedManagerPortfolioValueRoute
  '/manager/profile': typeof AuthenticatedManagerProfileRoute
  '/manager/public-page': typeof AuthenticatedManagerPublicPageRoute
  '/manager/requests': typeof AuthenticatedManagerRequestsRoute
  '/manager/tax': typeof AuthenticatedManagerTaxRoute
  '/manager/timeline': typeof AuthenticatedManagerTimelineRoute
  '/manager/wires': typeof AuthenticatedManagerWiresRoute
  '/onboarding/accreditation': typeof AuthenticatedOnboardingAccreditationRoute
  '/onboarding/aml': typeof AuthenticatedOnboardingAmlRoute
  '/onboarding/documents': typeof AuthenticatedOnboardingDocumentsRoute
  '/onboarding/funding': typeof AuthenticatedOnboardingFundingRoute
  '/onboarding/kyc': typeof AuthenticatedOnboardingKycRoute
  '/ops/banking': typeof AuthenticatedOpsBankingRoute
  '/ops/ss4': typeof AuthenticatedOpsSs4Route
  '/ops/tax-documents': typeof AuthenticatedOpsTaxDocumentsRoute
  '/ops/team': typeof AuthenticatedOpsTeamRoute
  '/api/public/login-attempt': typeof ApiPublicLoginAttemptRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/diligence/': typeof AuthenticatedDiligenceIndexRoute
  '/manager/': typeof AuthenticatedManagerIndexRoute
  '/ops/': typeof AuthenticatedOpsIndexRoute
  '/admin/contracts/$clientId': typeof AuthenticatedAdminContractsClientIdRoute
  '/admin/fund/$fundId': typeof AuthenticatedAdminFundFundIdRoute
  '/admin/packet/$fundId': typeof AuthenticatedAdminPacketFundIdRoute
  '/manager/fund/$fundId': typeof AuthenticatedManagerFundFundIdRoute
  '/ops/funds/$fundId': typeof AuthenticatedOpsFundsFundIdRoute
  '/api/public/email/click': typeof ApiPublicEmailClickRoute
  '/api/public/email/open': typeof ApiPublicEmailOpenRoute
  '/api/public/notify/drain': typeof ApiPublicNotifyDrainRoute
  '/api/public/packet/$token': typeof ApiPublicPacketTokenRoute
  '/api/public/webhooks/box-sign': typeof ApiPublicWebhooksBoxSignRoute
  '/api/public/webhooks/didit': typeof ApiPublicWebhooksDiditRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/contracts/': typeof AuthenticatedAdminContractsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/fund-administration': typeof FundAdministrationRoute
  '/manager-login': typeof ManagerLoginRoute
  '/platform': typeof PlatformRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spv': typeof SpvRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/apply': typeof AuthenticatedApplyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/fund-documents': typeof AuthenticatedFundDocumentsRoute
  '/fund-memo': typeof AuthenticatedFundMemoRoute
  '/home': typeof AuthenticatedHomeRoute
  '/my-portfolio': typeof AuthenticatedMyPortfolioRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/wire': typeof AuthenticatedWireRoute
  '/wire-confirmation': typeof AuthenticatedWireConfirmationRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/register': typeof AuthRegisterRoute
  '/fund/$slug': typeof FundSlugRoute
  '/auth': typeof AuthIndexRoute
  '/admin/$applicationId': typeof AuthenticatedAdminApplicationIdRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/cap-table': typeof AuthenticatedAdminCapTableRoute
  '/admin/cap-table-board': typeof AuthenticatedAdminCapTableBoardRoute
  '/admin/document-log': typeof AuthenticatedAdminDocumentLogRoute
  '/admin/email-preview': typeof AuthenticatedAdminEmailPreviewRoute
  '/admin/funding': typeof AuthenticatedAdminFundingRoute
  '/admin/funds': typeof AuthenticatedAdminFundsRoute
  '/admin/funnel': typeof AuthenticatedAdminFunnelRoute
  '/admin/investors': typeof AuthenticatedAdminInvestorsRoute
  '/admin/memo': typeof AuthenticatedAdminMemoRoute
  '/admin/new-application': typeof AuthenticatedAdminNewApplicationRoute
  '/admin/offering-statement': typeof AuthenticatedAdminOfferingStatementRoute
  '/admin/performance': typeof AuthenticatedAdminPerformanceRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/portfolio-value': typeof AuthenticatedAdminPortfolioValueRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/admin/timeline': typeof AuthenticatedAdminTimelineRoute
  '/admin/wire': typeof AuthenticatedAdminWireRoute
  '/diligence/$offeringId': typeof AuthenticatedDiligenceOfferingIdRoute
  '/manager/$applicationId': typeof AuthenticatedManagerApplicationIdRoute
  '/manager/activity': typeof AuthenticatedManagerActivityRoute
  '/manager/approvals': typeof AuthenticatedManagerApprovalsRoute
  '/manager/cap-table': typeof AuthenticatedManagerCapTableRoute
  '/manager/cap-table-board': typeof AuthenticatedManagerCapTableBoardRoute
  '/manager/closing': typeof AuthenticatedManagerClosingRoute
  '/manager/diligence': typeof AuthenticatedManagerDiligenceRoute
  '/manager/documents': typeof AuthenticatedManagerDocumentsRoute
  '/manager/inbox': typeof AuthenticatedManagerInboxRoute
  '/manager/investors': typeof AuthenticatedManagerInvestorsRoute
  '/manager/memo': typeof AuthenticatedManagerMemoRoute
  '/manager/messages': typeof AuthenticatedManagerMessagesRoute
  '/manager/offering-statement': typeof AuthenticatedManagerOfferingStatementRoute
  '/manager/onboarding': typeof AuthenticatedManagerOnboardingRoute
  '/manager/performance': typeof AuthenticatedManagerPerformanceRoute
  '/manager/permissions': typeof AuthenticatedManagerPermissionsRoute
  '/manager/portfolio-value': typeof AuthenticatedManagerPortfolioValueRoute
  '/manager/profile': typeof AuthenticatedManagerProfileRoute
  '/manager/public-page': typeof AuthenticatedManagerPublicPageRoute
  '/manager/requests': typeof AuthenticatedManagerRequestsRoute
  '/manager/tax': typeof AuthenticatedManagerTaxRoute
  '/manager/timeline': typeof AuthenticatedManagerTimelineRoute
  '/manager/wires': typeof AuthenticatedManagerWiresRoute
  '/onboarding/accreditation': typeof AuthenticatedOnboardingAccreditationRoute
  '/onboarding/aml': typeof AuthenticatedOnboardingAmlRoute
  '/onboarding/documents': typeof AuthenticatedOnboardingDocumentsRoute
  '/onboarding/funding': typeof AuthenticatedOnboardingFundingRoute
  '/onboarding/kyc': typeof AuthenticatedOnboardingKycRoute
  '/ops/banking': typeof AuthenticatedOpsBankingRoute
  '/ops/ss4': typeof AuthenticatedOpsSs4Route
  '/ops/tax-documents': typeof AuthenticatedOpsTaxDocumentsRoute
  '/ops/team': typeof AuthenticatedOpsTeamRoute
  '/api/public/login-attempt': typeof ApiPublicLoginAttemptRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/diligence': typeof AuthenticatedDiligenceIndexRoute
  '/manager': typeof AuthenticatedManagerIndexRoute
  '/ops': typeof AuthenticatedOpsIndexRoute
  '/admin/contracts/$clientId': typeof AuthenticatedAdminContractsClientIdRoute
  '/admin/fund/$fundId': typeof AuthenticatedAdminFundFundIdRoute
  '/admin/packet/$fundId': typeof AuthenticatedAdminPacketFundIdRoute
  '/manager/fund/$fundId': typeof AuthenticatedManagerFundFundIdRoute
  '/ops/funds/$fundId': typeof AuthenticatedOpsFundsFundIdRoute
  '/api/public/email/click': typeof ApiPublicEmailClickRoute
  '/api/public/email/open': typeof ApiPublicEmailOpenRoute
  '/api/public/notify/drain': typeof ApiPublicNotifyDrainRoute
  '/api/public/packet/$token': typeof ApiPublicPacketTokenRoute
  '/api/public/webhooks/box-sign': typeof ApiPublicWebhooksBoxSignRoute
  '/api/public/webhooks/didit': typeof ApiPublicWebhooksDiditRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/contracts': typeof AuthenticatedAdminContractsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/fund-administration': typeof FundAdministrationRoute
  '/manager-login': typeof ManagerLoginRoute
  '/platform': typeof PlatformRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spv': typeof SpvRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/apply': typeof AuthenticatedApplyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/fund-documents': typeof AuthenticatedFundDocumentsRoute
  '/_authenticated/fund-memo': typeof AuthenticatedFundMemoRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/my-portfolio': typeof AuthenticatedMyPortfolioRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/wire': typeof AuthenticatedWireRoute
  '/_authenticated/wire-confirmation': typeof AuthenticatedWireConfirmationRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/register': typeof AuthRegisterRoute
  '/fund/$slug': typeof FundSlugRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/admin/$applicationId': typeof AuthenticatedAdminApplicationIdRoute
  '/_authenticated/admin/access': typeof AuthenticatedAdminAccessRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/cap-table': typeof AuthenticatedAdminCapTableRoute
  '/_authenticated/admin/cap-table-board': typeof AuthenticatedAdminCapTableBoardRoute
  '/_authenticated/admin/document-log': typeof AuthenticatedAdminDocumentLogRoute
  '/_authenticated/admin/email-preview': typeof AuthenticatedAdminEmailPreviewRoute
  '/_authenticated/admin/funding': typeof AuthenticatedAdminFundingRoute
  '/_authenticated/admin/funds': typeof AuthenticatedAdminFundsRoute
  '/_authenticated/admin/funnel': typeof AuthenticatedAdminFunnelRoute
  '/_authenticated/admin/investors': typeof AuthenticatedAdminInvestorsRoute
  '/_authenticated/admin/memo': typeof AuthenticatedAdminMemoRoute
  '/_authenticated/admin/new-application': typeof AuthenticatedAdminNewApplicationRoute
  '/_authenticated/admin/offering-statement': typeof AuthenticatedAdminOfferingStatementRoute
  '/_authenticated/admin/performance': typeof AuthenticatedAdminPerformanceRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/portfolio-value': typeof AuthenticatedAdminPortfolioValueRoute
  '/_authenticated/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/_authenticated/admin/timeline': typeof AuthenticatedAdminTimelineRoute
  '/_authenticated/admin/wire': typeof AuthenticatedAdminWireRoute
  '/_authenticated/diligence/$offeringId': typeof AuthenticatedDiligenceOfferingIdRoute
  '/_authenticated/manager/$applicationId': typeof AuthenticatedManagerApplicationIdRoute
  '/_authenticated/manager/activity': typeof AuthenticatedManagerActivityRoute
  '/_authenticated/manager/approvals': typeof AuthenticatedManagerApprovalsRoute
  '/_authenticated/manager/cap-table': typeof AuthenticatedManagerCapTableRoute
  '/_authenticated/manager/cap-table-board': typeof AuthenticatedManagerCapTableBoardRoute
  '/_authenticated/manager/closing': typeof AuthenticatedManagerClosingRoute
  '/_authenticated/manager/diligence': typeof AuthenticatedManagerDiligenceRoute
  '/_authenticated/manager/documents': typeof AuthenticatedManagerDocumentsRoute
  '/_authenticated/manager/inbox': typeof AuthenticatedManagerInboxRoute
  '/_authenticated/manager/investors': typeof AuthenticatedManagerInvestorsRoute
  '/_authenticated/manager/memo': typeof AuthenticatedManagerMemoRoute
  '/_authenticated/manager/messages': typeof AuthenticatedManagerMessagesRoute
  '/_authenticated/manager/offering-statement': typeof AuthenticatedManagerOfferingStatementRoute
  '/_authenticated/manager/onboarding': typeof AuthenticatedManagerOnboardingRoute
  '/_authenticated/manager/performance': typeof AuthenticatedManagerPerformanceRoute
  '/_authenticated/manager/permissions': typeof AuthenticatedManagerPermissionsRoute
  '/_authenticated/manager/portfolio-value': typeof AuthenticatedManagerPortfolioValueRoute
  '/_authenticated/manager/profile': typeof AuthenticatedManagerProfileRoute
  '/_authenticated/manager/public-page': typeof AuthenticatedManagerPublicPageRoute
  '/_authenticated/manager/requests': typeof AuthenticatedManagerRequestsRoute
  '/_authenticated/manager/tax': typeof AuthenticatedManagerTaxRoute
  '/_authenticated/manager/timeline': typeof AuthenticatedManagerTimelineRoute
  '/_authenticated/manager/wires': typeof AuthenticatedManagerWiresRoute
  '/_authenticated/onboarding/accreditation': typeof AuthenticatedOnboardingAccreditationRoute
  '/_authenticated/onboarding/aml': typeof AuthenticatedOnboardingAmlRoute
  '/_authenticated/onboarding/documents': typeof AuthenticatedOnboardingDocumentsRoute
  '/_authenticated/onboarding/funding': typeof AuthenticatedOnboardingFundingRoute
  '/_authenticated/onboarding/kyc': typeof AuthenticatedOnboardingKycRoute
  '/_authenticated/ops/banking': typeof AuthenticatedOpsBankingRoute
  '/_authenticated/ops/ss4': typeof AuthenticatedOpsSs4Route
  '/_authenticated/ops/tax-documents': typeof AuthenticatedOpsTaxDocumentsRoute
  '/_authenticated/ops/team': typeof AuthenticatedOpsTeamRoute
  '/api/public/login-attempt': typeof ApiPublicLoginAttemptRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/diligence/': typeof AuthenticatedDiligenceIndexRoute
  '/_authenticated/manager/': typeof AuthenticatedManagerIndexRoute
  '/_authenticated/ops/': typeof AuthenticatedOpsIndexRoute
  '/_authenticated/admin/contracts/$clientId': typeof AuthenticatedAdminContractsClientIdRoute
  '/_authenticated/admin/fund/$fundId': typeof AuthenticatedAdminFundFundIdRoute
  '/_authenticated/admin/packet/$fundId': typeof AuthenticatedAdminPacketFundIdRoute
  '/_authenticated/manager/fund/$fundId': typeof AuthenticatedManagerFundFundIdRoute
  '/_authenticated/ops/funds/$fundId': typeof AuthenticatedOpsFundsFundIdRoute
  '/api/public/email/click': typeof ApiPublicEmailClickRoute
  '/api/public/email/open': typeof ApiPublicEmailOpenRoute
  '/api/public/notify/drain': typeof ApiPublicNotifyDrainRoute
  '/api/public/packet/$token': typeof ApiPublicPacketTokenRoute
  '/api/public/webhooks/box-sign': typeof ApiPublicWebhooksBoxSignRoute
  '/api/public/webhooks/didit': typeof ApiPublicWebhooksDiditRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/admin/contracts/': typeof AuthenticatedAdminContractsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/fund-administration'
    | '/manager-login'
    | '/platform'
    | '/reset-password'
    | '/sitemap.xml'
    | '/spv'
    | '/accounts'
    | '/apply'
    | '/dashboard'
    | '/documents'
    | '/fund-documents'
    | '/fund-memo'
    | '/home'
    | '/my-portfolio'
    | '/portal'
    | '/subscription'
    | '/wire'
    | '/wire-confirmation'
    | '/auth/forgot'
    | '/auth/register'
    | '/fund/$slug'
    | '/auth/'
    | '/admin/$applicationId'
    | '/admin/access'
    | '/admin/activity'
    | '/admin/cap-table'
    | '/admin/cap-table-board'
    | '/admin/document-log'
    | '/admin/email-preview'
    | '/admin/funding'
    | '/admin/funds'
    | '/admin/funnel'
    | '/admin/investors'
    | '/admin/memo'
    | '/admin/new-application'
    | '/admin/offering-statement'
    | '/admin/performance'
    | '/admin/permissions'
    | '/admin/portfolio-value'
    | '/admin/requests'
    | '/admin/security'
    | '/admin/setup'
    | '/admin/timeline'
    | '/admin/wire'
    | '/diligence/$offeringId'
    | '/manager/$applicationId'
    | '/manager/activity'
    | '/manager/approvals'
    | '/manager/cap-table'
    | '/manager/cap-table-board'
    | '/manager/closing'
    | '/manager/diligence'
    | '/manager/documents'
    | '/manager/inbox'
    | '/manager/investors'
    | '/manager/memo'
    | '/manager/messages'
    | '/manager/offering-statement'
    | '/manager/onboarding'
    | '/manager/performance'
    | '/manager/permissions'
    | '/manager/portfolio-value'
    | '/manager/profile'
    | '/manager/public-page'
    | '/manager/requests'
    | '/manager/tax'
    | '/manager/timeline'
    | '/manager/wires'
    | '/onboarding/accreditation'
    | '/onboarding/aml'
    | '/onboarding/documents'
    | '/onboarding/funding'
    | '/onboarding/kyc'
    | '/ops/banking'
    | '/ops/ss4'
    | '/ops/tax-documents'
    | '/ops/team'
    | '/api/public/login-attempt'
    | '/lovable/email/events'
    | '/admin/'
    | '/diligence/'
    | '/manager/'
    | '/ops/'
    | '/admin/contracts/$clientId'
    | '/admin/fund/$fundId'
    | '/admin/packet/$fundId'
    | '/manager/fund/$fundId'
    | '/ops/funds/$fundId'
    | '/api/public/email/click'
    | '/api/public/email/open'
    | '/api/public/notify/drain'
    | '/api/public/packet/$token'
    | '/api/public/webhooks/box-sign'
    | '/api/public/webhooks/didit'
    | '/lovable/email/transactional/preview'
    | '/admin/contracts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/fund-administration'
    | '/manager-login'
    | '/platform'
    | '/reset-password'
    | '/sitemap.xml'
    | '/spv'
    | '/accounts'
    | '/apply'
    | '/dashboard'
    | '/documents'
    | '/fund-documents'
    | '/fund-memo'
    | '/home'
    | '/my-portfolio'
    | '/portal'
    | '/subscription'
    | '/wire'
    | '/wire-confirmation'
    | '/auth/forgot'
    | '/auth/register'
    | '/fund/$slug'
    | '/auth'
    | '/admin/$applicationId'
    | '/admin/access'
    | '/admin/activity'
    | '/admin/cap-table'
    | '/admin/cap-table-board'
    | '/admin/document-log'
    | '/admin/email-preview'
    | '/admin/funding'
    | '/admin/funds'
    | '/admin/funnel'
    | '/admin/investors'
    | '/admin/memo'
    | '/admin/new-application'
    | '/admin/offering-statement'
    | '/admin/performance'
    | '/admin/permissions'
    | '/admin/portfolio-value'
    | '/admin/requests'
    | '/admin/security'
    | '/admin/setup'
    | '/admin/timeline'
    | '/admin/wire'
    | '/diligence/$offeringId'
    | '/manager/$applicationId'
    | '/manager/activity'
    | '/manager/approvals'
    | '/manager/cap-table'
    | '/manager/cap-table-board'
    | '/manager/closing'
    | '/manager/diligence'
    | '/manager/documents'
    | '/manager/inbox'
    | '/manager/investors'
    | '/manager/memo'
    | '/manager/messages'
    | '/manager/offering-statement'
    | '/manager/onboarding'
    | '/manager/performance'
    | '/manager/permissions'
    | '/manager/portfolio-value'
    | '/manager/profile'
    | '/manager/public-page'
    | '/manager/requests'
    | '/manager/tax'
    | '/manager/timeline'
    | '/manager/wires'
    | '/onboarding/accreditation'
    | '/onboarding/aml'
    | '/onboarding/documents'
    | '/onboarding/funding'
    | '/onboarding/kyc'
    | '/ops/banking'
    | '/ops/ss4'
    | '/ops/tax-documents'
    | '/ops/team'
    | '/api/public/login-attempt'
    | '/lovable/email/events'
    | '/admin'
    | '/diligence'
    | '/manager'
    | '/ops'
    | '/admin/contracts/$clientId'
    | '/admin/fund/$fundId'
    | '/admin/packet/$fundId'
    | '/manager/fund/$fundId'
    | '/ops/funds/$fundId'
    | '/api/public/email/click'
    | '/api/public/email/open'
    | '/api/public/notify/drain'
    | '/api/public/packet/$token'
    | '/api/public/webhooks/box-sign'
    | '/api/public/webhooks/didit'
    | '/lovable/email/transactional/preview'
    | '/admin/contracts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/fund-administration'
    | '/manager-login'
    | '/platform'
    | '/reset-password'
    | '/sitemap.xml'
    | '/spv'
    | '/_authenticated/accounts'
    | '/_authenticated/apply'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/fund-documents'
    | '/_authenticated/fund-memo'
    | '/_authenticated/home'
    | '/_authenticated/my-portfolio'
    | '/_authenticated/portal'
    | '/_authenticated/subscription'
    | '/_authenticated/wire'
    | '/_authenticated/wire-confirmation'
    | '/auth/forgot'
    | '/auth/register'
    | '/fund/$slug'
    | '/auth/'
    | '/_authenticated/admin/$applicationId'
    | '/_authenticated/admin/access'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/cap-table'
    | '/_authenticated/admin/cap-table-board'
    | '/_authenticated/admin/document-log'
    | '/_authenticated/admin/email-preview'
    | '/_authenticated/admin/funding'
    | '/_authenticated/admin/funds'
    | '/_authenticated/admin/funnel'
    | '/_authenticated/admin/investors'
    | '/_authenticated/admin/memo'
    | '/_authenticated/admin/new-application'
    | '/_authenticated/admin/offering-statement'
    | '/_authenticated/admin/performance'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/portfolio-value'
    | '/_authenticated/admin/requests'
    | '/_authenticated/admin/security'
    | '/_authenticated/admin/setup'
    | '/_authenticated/admin/timeline'
    | '/_authenticated/admin/wire'
    | '/_authenticated/diligence/$offeringId'
    | '/_authenticated/manager/$applicationId'
    | '/_authenticated/manager/activity'
    | '/_authenticated/manager/approvals'
    | '/_authenticated/manager/cap-table'
    | '/_authenticated/manager/cap-table-board'
    | '/_authenticated/manager/closing'
    | '/_authenticated/manager/diligence'
    | '/_authenticated/manager/documents'
    | '/_authenticated/manager/inbox'
    | '/_authenticated/manager/investors'
    | '/_authenticated/manager/memo'
    | '/_authenticated/manager/messages'
    | '/_authenticated/manager/offering-statement'
    | '/_authenticated/manager/onboarding'
    | '/_authenticated/manager/performance'
    | '/_authenticated/manager/permissions'
    | '/_authenticated/manager/portfolio-value'
    | '/_authenticated/manager/profile'
    | '/_authenticated/manager/public-page'
    | '/_authenticated/manager/requests'
    | '/_authenticated/manager/tax'
    | '/_authenticated/manager/timeline'
    | '/_authenticated/manager/wires'
    | '/_authenticated/onboarding/accreditation'
    | '/_authenticated/onboarding/aml'
    | '/_authenticated/onboarding/documents'
    | '/_authenticated/onboarding/funding'
    | '/_authenticated/onboarding/kyc'
    | '/_authenticated/ops/banking'
    | '/_authenticated/ops/ss4'
    | '/_authenticated/ops/tax-documents'
    | '/_authenticated/ops/team'
    | '/api/public/login-attempt'
    | '/lovable/email/events'
    | '/_authenticated/admin/'
    | '/_authenticated/diligence/'
    | '/_authenticated/manager/'
    | '/_authenticated/ops/'
    | '/_authenticated/admin/contracts/$clientId'
    | '/_authenticated/admin/fund/$fundId'
    | '/_authenticated/admin/packet/$fundId'
    | '/_authenticated/manager/fund/$fundId'
    | '/_authenticated/ops/funds/$fundId'
    | '/api/public/email/click'
    | '/api/public/email/open'
    | '/api/public/notify/drain'
    | '/api/public/packet/$token'
    | '/api/public/webhooks/box-sign'
    | '/api/public/webhooks/didit'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/admin/contracts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  FundAdministrationRoute: typeof FundAdministrationRoute
  ManagerLoginRoute: typeof ManagerLoginRoute
  PlatformRoute: typeof PlatformRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpvRoute: typeof SpvRoute
  FundSlugRoute: typeof FundSlugRoute
  ApiPublicLoginAttemptRoute: typeof ApiPublicLoginAttemptRoute
  LovableEmailEventsRoute: typeof LovableEmailEventsRoute
  ApiPublicEmailClickRoute: typeof ApiPublicEmailClickRoute
  ApiPublicEmailOpenRoute: typeof ApiPublicEmailOpenRoute
  ApiPublicNotifyDrainRoute: typeof ApiPublicNotifyDrainRoute
  ApiPublicPacketTokenRoute: typeof ApiPublicPacketTokenRoute
  ApiPublicWebhooksBoxSignRoute: typeof ApiPublicWebhooksBoxSignRoute
  ApiPublicWebhooksDiditRoute: typeof ApiPublicWebhooksDiditRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund-administration': {
      id: '/fund-administration'
      path: '/fund-administration'
      fullPath: '/fund-administration'
      preLoaderRoute: typeof FundAdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-login': {
      id: '/manager-login'
      path: '/manager-login'
      fullPath: '/manager-login'
      preLoaderRoute: typeof ManagerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spv': {
      id: '/spv'
      path: '/spv'
      fullPath: '/spv'
      preLoaderRoute: typeof SpvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apply': {
      id: '/_authenticated/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof AuthenticatedApplyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund-documents': {
      id: '/_authenticated/fund-documents'
      path: '/fund-documents'
      fullPath: '/fund-documents'
      preLoaderRoute: typeof AuthenticatedFundDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund-memo': {
      id: '/_authenticated/fund-memo'
      path: '/fund-memo'
      fullPath: '/fund-memo'
      preLoaderRoute: typeof AuthenticatedFundMemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-portfolio': {
      id: '/_authenticated/my-portfolio'
      path: '/my-portfolio'
      fullPath: '/my-portfolio'
      preLoaderRoute: typeof AuthenticatedMyPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wire': {
      id: '/_authenticated/wire'
      path: '/wire'
      fullPath: '/wire'
      preLoaderRoute: typeof AuthenticatedWireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wire-confirmation': {
      id: '/_authenticated/wire-confirmation'
      path: '/wire-confirmation'
      fullPath: '/wire-confirmation'
      preLoaderRoute: typeof AuthenticatedWireConfirmationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/fund/$slug': {
      id: '/fund/$slug'
      path: '/fund/$slug'
      fullPath: '/fund/$slug'
      preLoaderRoute: typeof FundSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$applicationId': {
      id: '/_authenticated/admin/$applicationId'
      path: '/admin/$applicationId'
      fullPath: '/admin/$applicationId'
      preLoaderRoute: typeof AuthenticatedAdminApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/access': {
      id: '/_authenticated/admin/access'
      path: '/admin/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AuthenticatedAdminAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cap-table': {
      id: '/_authenticated/admin/cap-table'
      path: '/admin/cap-table'
      fullPath: '/admin/cap-table'
      preLoaderRoute: typeof AuthenticatedAdminCapTableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cap-table-board': {
      id: '/_authenticated/admin/cap-table-board'
      path: '/admin/cap-table-board'
      fullPath: '/admin/cap-table-board'
      preLoaderRoute: typeof AuthenticatedAdminCapTableBoardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/document-log': {
      id: '/_authenticated/admin/document-log'
      path: '/admin/document-log'
      fullPath: '/admin/document-log'
      preLoaderRoute: typeof AuthenticatedAdminDocumentLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/email-preview': {
      id: '/_authenticated/admin/email-preview'
      path: '/admin/email-preview'
      fullPath: '/admin/email-preview'
      preLoaderRoute: typeof AuthenticatedAdminEmailPreviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/funding': {
      id: '/_authenticated/admin/funding'
      path: '/admin/funding'
      fullPath: '/admin/funding'
      preLoaderRoute: typeof AuthenticatedAdminFundingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/funds': {
      id: '/_authenticated/admin/funds'
      path: '/admin/funds'
      fullPath: '/admin/funds'
      preLoaderRoute: typeof AuthenticatedAdminFundsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/funnel': {
      id: '/_authenticated/admin/funnel'
      path: '/admin/funnel'
      fullPath: '/admin/funnel'
      preLoaderRoute: typeof AuthenticatedAdminFunnelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/investors': {
      id: '/_authenticated/admin/investors'
      path: '/admin/investors'
      fullPath: '/admin/investors'
      preLoaderRoute: typeof AuthenticatedAdminInvestorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/memo': {
      id: '/_authenticated/admin/memo'
      path: '/admin/memo'
      fullPath: '/admin/memo'
      preLoaderRoute: typeof AuthenticatedAdminMemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/new-application': {
      id: '/_authenticated/admin/new-application'
      path: '/admin/new-application'
      fullPath: '/admin/new-application'
      preLoaderRoute: typeof AuthenticatedAdminNewApplicationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/offering-statement': {
      id: '/_authenticated/admin/offering-statement'
      path: '/admin/offering-statement'
      fullPath: '/admin/offering-statement'
      preLoaderRoute: typeof AuthenticatedAdminOfferingStatementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/performance': {
      id: '/_authenticated/admin/performance'
      path: '/admin/performance'
      fullPath: '/admin/performance'
      preLoaderRoute: typeof AuthenticatedAdminPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/portfolio-value': {
      id: '/_authenticated/admin/portfolio-value'
      path: '/admin/portfolio-value'
      fullPath: '/admin/portfolio-value'
      preLoaderRoute: typeof AuthenticatedAdminPortfolioValueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/requests': {
      id: '/_authenticated/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/setup': {
      id: '/_authenticated/admin/setup'
      path: '/admin/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AuthenticatedAdminSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/timeline': {
      id: '/_authenticated/admin/timeline'
      path: '/admin/timeline'
      fullPath: '/admin/timeline'
      preLoaderRoute: typeof AuthenticatedAdminTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/wire': {
      id: '/_authenticated/admin/wire'
      path: '/admin/wire'
      fullPath: '/admin/wire'
      preLoaderRoute: typeof AuthenticatedAdminWireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diligence/': {
      id: '/_authenticated/diligence/'
      path: '/diligence'
      fullPath: '/diligence/'
      preLoaderRoute: typeof AuthenticatedDiligenceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diligence/$offeringId': {
      id: '/_authenticated/diligence/$offeringId'
      path: '/diligence/$offeringId'
      fullPath: '/diligence/$offeringId'
      preLoaderRoute: typeof AuthenticatedDiligenceOfferingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/': {
      id: '/_authenticated/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof AuthenticatedManagerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/$applicationId': {
      id: '/_authenticated/manager/$applicationId'
      path: '/manager/$applicationId'
      fullPath: '/manager/$applicationId'
      preLoaderRoute: typeof AuthenticatedManagerApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/activity': {
      id: '/_authenticated/manager/activity'
      path: '/manager/activity'
      fullPath: '/manager/activity'
      preLoaderRoute: typeof AuthenticatedManagerActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/approvals': {
      id: '/_authenticated/manager/approvals'
      path: '/manager/approvals'
      fullPath: '/manager/approvals'
      preLoaderRoute: typeof AuthenticatedManagerApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/cap-table': {
      id: '/_authenticated/manager/cap-table'
      path: '/manager/cap-table'
      fullPath: '/manager/cap-table'
      preLoaderRoute: typeof AuthenticatedManagerCapTableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/cap-table-board': {
      id: '/_authenticated/manager/cap-table-board'
      path: '/manager/cap-table-board'
      fullPath: '/manager/cap-table-board'
      preLoaderRoute: typeof AuthenticatedManagerCapTableBoardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/closing': {
      id: '/_authenticated/manager/closing'
      path: '/manager/closing'
      fullPath: '/manager/closing'
      preLoaderRoute: typeof AuthenticatedManagerClosingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/diligence': {
      id: '/_authenticated/manager/diligence'
      path: '/manager/diligence'
      fullPath: '/manager/diligence'
      preLoaderRoute: typeof AuthenticatedManagerDiligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/documents': {
      id: '/_authenticated/manager/documents'
      path: '/manager/documents'
      fullPath: '/manager/documents'
      preLoaderRoute: typeof AuthenticatedManagerDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/inbox': {
      id: '/_authenticated/manager/inbox'
      path: '/manager/inbox'
      fullPath: '/manager/inbox'
      preLoaderRoute: typeof AuthenticatedManagerInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/investors': {
      id: '/_authenticated/manager/investors'
      path: '/manager/investors'
      fullPath: '/manager/investors'
      preLoaderRoute: typeof AuthenticatedManagerInvestorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/memo': {
      id: '/_authenticated/manager/memo'
      path: '/manager/memo'
      fullPath: '/manager/memo'
      preLoaderRoute: typeof AuthenticatedManagerMemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/messages': {
      id: '/_authenticated/manager/messages'
      path: '/manager/messages'
      fullPath: '/manager/messages'
      preLoaderRoute: typeof AuthenticatedManagerMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/offering-statement': {
      id: '/_authenticated/manager/offering-statement'
      path: '/manager/offering-statement'
      fullPath: '/manager/offering-statement'
      preLoaderRoute: typeof AuthenticatedManagerOfferingStatementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/onboarding': {
      id: '/_authenticated/manager/onboarding'
      path: '/manager/onboarding'
      fullPath: '/manager/onboarding'
      preLoaderRoute: typeof AuthenticatedManagerOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/performance': {
      id: '/_authenticated/manager/performance'
      path: '/manager/performance'
      fullPath: '/manager/performance'
      preLoaderRoute: typeof AuthenticatedManagerPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/permissions': {
      id: '/_authenticated/manager/permissions'
      path: '/manager/permissions'
      fullPath: '/manager/permissions'
      preLoaderRoute: typeof AuthenticatedManagerPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/portfolio-value': {
      id: '/_authenticated/manager/portfolio-value'
      path: '/manager/portfolio-value'
      fullPath: '/manager/portfolio-value'
      preLoaderRoute: typeof AuthenticatedManagerPortfolioValueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/profile': {
      id: '/_authenticated/manager/profile'
      path: '/manager/profile'
      fullPath: '/manager/profile'
      preLoaderRoute: typeof AuthenticatedManagerProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/public-page': {
      id: '/_authenticated/manager/public-page'
      path: '/manager/public-page'
      fullPath: '/manager/public-page'
      preLoaderRoute: typeof AuthenticatedManagerPublicPageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/requests': {
      id: '/_authenticated/manager/requests'
      path: '/manager/requests'
      fullPath: '/manager/requests'
      preLoaderRoute: typeof AuthenticatedManagerRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/tax': {
      id: '/_authenticated/manager/tax'
      path: '/manager/tax'
      fullPath: '/manager/tax'
      preLoaderRoute: typeof AuthenticatedManagerTaxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/timeline': {
      id: '/_authenticated/manager/timeline'
      path: '/manager/timeline'
      fullPath: '/manager/timeline'
      preLoaderRoute: typeof AuthenticatedManagerTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/wires': {
      id: '/_authenticated/manager/wires'
      path: '/manager/wires'
      fullPath: '/manager/wires'
      preLoaderRoute: typeof AuthenticatedManagerWiresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/accreditation': {
      id: '/_authenticated/onboarding/accreditation'
      path: '/onboarding/accreditation'
      fullPath: '/onboarding/accreditation'
      preLoaderRoute: typeof AuthenticatedOnboardingAccreditationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/aml': {
      id: '/_authenticated/onboarding/aml'
      path: '/onboarding/aml'
      fullPath: '/onboarding/aml'
      preLoaderRoute: typeof AuthenticatedOnboardingAmlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/documents': {
      id: '/_authenticated/onboarding/documents'
      path: '/onboarding/documents'
      fullPath: '/onboarding/documents'
      preLoaderRoute: typeof AuthenticatedOnboardingDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/funding': {
      id: '/_authenticated/onboarding/funding'
      path: '/onboarding/funding'
      fullPath: '/onboarding/funding'
      preLoaderRoute: typeof AuthenticatedOnboardingFundingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/kyc': {
      id: '/_authenticated/onboarding/kyc'
      path: '/onboarding/kyc'
      fullPath: '/onboarding/kyc'
      preLoaderRoute: typeof AuthenticatedOnboardingKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ops/': {
      id: '/_authenticated/ops/'
      path: '/ops'
      fullPath: '/ops/'
      preLoaderRoute: typeof AuthenticatedOpsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ops/banking': {
      id: '/_authenticated/ops/banking'
      path: '/ops/banking'
      fullPath: '/ops/banking'
      preLoaderRoute: typeof AuthenticatedOpsBankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ops/ss4': {
      id: '/_authenticated/ops/ss4'
      path: '/ops/ss4'
      fullPath: '/ops/ss4'
      preLoaderRoute: typeof AuthenticatedOpsSs4RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ops/tax-documents': {
      id: '/_authenticated/ops/tax-documents'
      path: '/ops/tax-documents'
      fullPath: '/ops/tax-documents'
      preLoaderRoute: typeof AuthenticatedOpsTaxDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ops/team': {
      id: '/_authenticated/ops/team'
      path: '/ops/team'
      fullPath: '/ops/team'
      preLoaderRoute: typeof AuthenticatedOpsTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/login-attempt': {
      id: '/api/public/login-attempt'
      path: '/api/public/login-attempt'
      fullPath: '/api/public/login-attempt'
      preLoaderRoute: typeof ApiPublicLoginAttemptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/events': {
      id: '/lovable/email/events'
      path: '/lovable/email/events'
      fullPath: '/lovable/email/events'
      preLoaderRoute: typeof LovableEmailEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/contracts/': {
      id: '/_authenticated/admin/contracts/'
      path: '/admin/contracts'
      fullPath: '/admin/contracts/'
      preLoaderRoute: typeof AuthenticatedAdminContractsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/contracts/$clientId': {
      id: '/_authenticated/admin/contracts/$clientId'
      path: '/admin/contracts/$clientId'
      fullPath: '/admin/contracts/$clientId'
      preLoaderRoute: typeof AuthenticatedAdminContractsClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/fund/$fundId': {
      id: '/_authenticated/admin/fund/$fundId'
      path: '/admin/fund/$fundId'
      fullPath: '/admin/fund/$fundId'
      preLoaderRoute: typeof AuthenticatedAdminFundFundIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/packet/$fundId': {
      id: '/_authenticated/admin/packet/$fundId'
      path: '/admin/packet/$fundId'
      fullPath: '/admin/packet/$fundId'
      preLoaderRoute: typeof AuthenticatedAdminPacketFundIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/fund/$fundId': {
      id: '/_authenticated/manager/fund/$fundId'
      path: '/manager/fund/$fundId'
      fullPath: '/manager/fund/$fundId'
      preLoaderRoute: typeof AuthenticatedManagerFundFundIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ops/funds/$fundId': {
      id: '/_authenticated/ops/funds/$fundId'
      path: '/ops/funds/$fundId'
      fullPath: '/ops/funds/$fundId'
      preLoaderRoute: typeof AuthenticatedOpsFundsFundIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/email/click': {
      id: '/api/public/email/click'
      path: '/api/public/email/click'
      fullPath: '/api/public/email/click'
      preLoaderRoute: typeof ApiPublicEmailClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email/open': {
      id: '/api/public/email/open'
      path: '/api/public/email/open'
      fullPath: '/api/public/email/open'
      preLoaderRoute: typeof ApiPublicEmailOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify/drain': {
      id: '/api/public/notify/drain'
      path: '/api/public/notify/drain'
      fullPath: '/api/public/notify/drain'
      preLoaderRoute: typeof ApiPublicNotifyDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/packet/$token': {
      id: '/api/public/packet/$token'
      path: '/api/public/packet/$token'
      fullPath: '/api/public/packet/$token'
      preLoaderRoute: typeof ApiPublicPacketTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/box-sign': {
      id: '/api/public/webhooks/box-sign'
      path: '/api/public/webhooks/box-sign'
      fullPath: '/api/public/webhooks/box-sign'
      preLoaderRoute: typeof ApiPublicWebhooksBoxSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/didit': {
      id: '/api/public/webhooks/didit'
      path: '/api/public/webhooks/didit'
      fullPath: '/api/public/webhooks/didit'
      preLoaderRoute: typeof ApiPublicWebhooksDiditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedApplyRoute: typeof AuthenticatedApplyRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFundDocumentsRoute: typeof AuthenticatedFundDocumentsRoute
  AuthenticatedFundMemoRoute: typeof AuthenticatedFundMemoRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMyPortfolioRoute: typeof AuthenticatedMyPortfolioRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedWireRoute: typeof AuthenticatedWireRoute
  AuthenticatedWireConfirmationRoute: typeof AuthenticatedWireConfirmationRoute
  AuthenticatedAdminApplicationIdRoute: typeof AuthenticatedAdminApplicationIdRoute
  AuthenticatedAdminAccessRoute: typeof AuthenticatedAdminAccessRoute
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminCapTableRoute: typeof AuthenticatedAdminCapTableRoute
  AuthenticatedAdminCapTableBoardRoute: typeof AuthenticatedAdminCapTableBoardRoute
  AuthenticatedAdminDocumentLogRoute: typeof AuthenticatedAdminDocumentLogRoute
  AuthenticatedAdminEmailPreviewRoute: typeof AuthenticatedAdminEmailPreviewRoute
  AuthenticatedAdminFundingRoute: typeof AuthenticatedAdminFundingRoute
  AuthenticatedAdminFundsRoute: typeof AuthenticatedAdminFundsRoute
  AuthenticatedAdminFunnelRoute: typeof AuthenticatedAdminFunnelRoute
  AuthenticatedAdminInvestorsRoute: typeof AuthenticatedAdminInvestorsRoute
  AuthenticatedAdminMemoRoute: typeof AuthenticatedAdminMemoRoute
  AuthenticatedAdminNewApplicationRoute: typeof AuthenticatedAdminNewApplicationRoute
  AuthenticatedAdminOfferingStatementRoute: typeof AuthenticatedAdminOfferingStatementRoute
  AuthenticatedAdminPerformanceRoute: typeof AuthenticatedAdminPerformanceRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminPortfolioValueRoute: typeof AuthenticatedAdminPortfolioValueRoute
  AuthenticatedAdminRequestsRoute: typeof AuthenticatedAdminRequestsRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminSetupRoute: typeof AuthenticatedAdminSetupRoute
  AuthenticatedAdminTimelineRoute: typeof AuthenticatedAdminTimelineRoute
  AuthenticatedAdminWireRoute: typeof AuthenticatedAdminWireRoute
  AuthenticatedDiligenceOfferingIdRoute: typeof AuthenticatedDiligenceOfferingIdRoute
  AuthenticatedManagerApplicationIdRoute: typeof AuthenticatedManagerApplicationIdRoute
  AuthenticatedManagerActivityRoute: typeof AuthenticatedManagerActivityRoute
  AuthenticatedManagerApprovalsRoute: typeof AuthenticatedManagerApprovalsRoute
  AuthenticatedManagerCapTableRoute: typeof AuthenticatedManagerCapTableRoute
  AuthenticatedManagerCapTableBoardRoute: typeof AuthenticatedManagerCapTableBoardRoute
  AuthenticatedManagerClosingRoute: typeof AuthenticatedManagerClosingRoute
  AuthenticatedManagerDiligenceRoute: typeof AuthenticatedManagerDiligenceRoute
  AuthenticatedManagerDocumentsRoute: typeof AuthenticatedManagerDocumentsRoute
  AuthenticatedManagerInboxRoute: typeof AuthenticatedManagerInboxRoute
  AuthenticatedManagerInvestorsRoute: typeof AuthenticatedManagerInvestorsRoute
  AuthenticatedManagerMemoRoute: typeof AuthenticatedManagerMemoRoute
  AuthenticatedManagerMessagesRoute: typeof AuthenticatedManagerMessagesRoute
  AuthenticatedManagerOfferingStatementRoute: typeof AuthenticatedManagerOfferingStatementRoute
  AuthenticatedManagerOnboardingRoute: typeof AuthenticatedManagerOnboardingRoute
  AuthenticatedManagerPerformanceRoute: typeof AuthenticatedManagerPerformanceRoute
  AuthenticatedManagerPermissionsRoute: typeof AuthenticatedManagerPermissionsRoute
  AuthenticatedManagerPortfolioValueRoute: typeof AuthenticatedManagerPortfolioValueRoute
  AuthenticatedManagerProfileRoute: typeof AuthenticatedManagerProfileRoute
  AuthenticatedManagerPublicPageRoute: typeof AuthenticatedManagerPublicPageRoute
  AuthenticatedManagerRequestsRoute: typeof AuthenticatedManagerRequestsRoute
  AuthenticatedManagerTaxRoute: typeof AuthenticatedManagerTaxRoute
  AuthenticatedManagerTimelineRoute: typeof AuthenticatedManagerTimelineRoute
  AuthenticatedManagerWiresRoute: typeof AuthenticatedManagerWiresRoute
  AuthenticatedOnboardingAccreditationRoute: typeof AuthenticatedOnboardingAccreditationRoute
  AuthenticatedOnboardingAmlRoute: typeof AuthenticatedOnboardingAmlRoute
  AuthenticatedOnboardingDocumentsRoute: typeof AuthenticatedOnboardingDocumentsRoute
  AuthenticatedOnboardingFundingRoute: typeof AuthenticatedOnboardingFundingRoute
  AuthenticatedOnboardingKycRoute: typeof AuthenticatedOnboardingKycRoute
  AuthenticatedOpsBankingRoute: typeof AuthenticatedOpsBankingRoute
  AuthenticatedOpsSs4Route: typeof AuthenticatedOpsSs4Route
  AuthenticatedOpsTaxDocumentsRoute: typeof AuthenticatedOpsTaxDocumentsRoute
  AuthenticatedOpsTeamRoute: typeof AuthenticatedOpsTeamRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedDiligenceIndexRoute: typeof AuthenticatedDiligenceIndexRoute
  AuthenticatedManagerIndexRoute: typeof AuthenticatedManagerIndexRoute
  AuthenticatedOpsIndexRoute: typeof AuthenticatedOpsIndexRoute
  AuthenticatedAdminContractsClientIdRoute: typeof AuthenticatedAdminContractsClientIdRoute
  AuthenticatedAdminFundFundIdRoute: typeof AuthenticatedAdminFundFundIdRoute
  AuthenticatedAdminPacketFundIdRoute: typeof AuthenticatedAdminPacketFundIdRoute
  AuthenticatedManagerFundFundIdRoute: typeof AuthenticatedManagerFundFundIdRoute
  AuthenticatedOpsFundsFundIdRoute: typeof AuthenticatedOpsFundsFundIdRoute
  AuthenticatedAdminContractsIndexRoute: typeof AuthenticatedAdminContractsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedApplyRoute: AuthenticatedApplyRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFundDocumentsRoute: AuthenticatedFundDocumentsRoute,
  AuthenticatedFundMemoRoute: AuthenticatedFundMemoRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMyPortfolioRoute: AuthenticatedMyPortfolioRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedWireRoute: AuthenticatedWireRoute,
  AuthenticatedWireConfirmationRoute: AuthenticatedWireConfirmationRoute,
  AuthenticatedAdminApplicationIdRoute: AuthenticatedAdminApplicationIdRoute,
  AuthenticatedAdminAccessRoute: AuthenticatedAdminAccessRoute,
  AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
  AuthenticatedAdminCapTableRoute: AuthenticatedAdminCapTableRoute,
  AuthenticatedAdminCapTableBoardRoute: AuthenticatedAdminCapTableBoardRoute,
  AuthenticatedAdminDocumentLogRoute: AuthenticatedAdminDocumentLogRoute,
  AuthenticatedAdminEmailPreviewRoute: AuthenticatedAdminEmailPreviewRoute,
  AuthenticatedAdminFundingRoute: AuthenticatedAdminFundingRoute,
  AuthenticatedAdminFundsRoute: AuthenticatedAdminFundsRoute,
  AuthenticatedAdminFunnelRoute: AuthenticatedAdminFunnelRoute,
  AuthenticatedAdminInvestorsRoute: AuthenticatedAdminInvestorsRoute,
  AuthenticatedAdminMemoRoute: AuthenticatedAdminMemoRoute,
  AuthenticatedAdminNewApplicationRoute: AuthenticatedAdminNewApplicationRoute,
  AuthenticatedAdminOfferingStatementRoute:
    AuthenticatedAdminOfferingStatementRoute,
  AuthenticatedAdminPerformanceRoute: AuthenticatedAdminPerformanceRoute,
  AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
  AuthenticatedAdminPortfolioValueRoute: AuthenticatedAdminPortfolioValueRoute,
  AuthenticatedAdminRequestsRoute: AuthenticatedAdminRequestsRoute,
  AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
  AuthenticatedAdminSetupRoute: AuthenticatedAdminSetupRoute,
  AuthenticatedAdminTimelineRoute: AuthenticatedAdminTimelineRoute,
  AuthenticatedAdminWireRoute: AuthenticatedAdminWireRoute,
  AuthenticatedDiligenceOfferingIdRoute: AuthenticatedDiligenceOfferingIdRoute,
  AuthenticatedManagerApplicationIdRoute:
    AuthenticatedManagerApplicationIdRoute,
  AuthenticatedManagerActivityRoute: AuthenticatedManagerActivityRoute,
  AuthenticatedManagerApprovalsRoute: AuthenticatedManagerApprovalsRoute,
  AuthenticatedManagerCapTableRoute: AuthenticatedManagerCapTableRoute,
  AuthenticatedManagerCapTableBoardRoute:
    AuthenticatedManagerCapTableBoardRoute,
  AuthenticatedManagerClosingRoute: AuthenticatedManagerClosingRoute,
  AuthenticatedManagerDiligenceRoute: AuthenticatedManagerDiligenceRoute,
  AuthenticatedManagerDocumentsRoute: AuthenticatedManagerDocumentsRoute,
  AuthenticatedManagerInboxRoute: AuthenticatedManagerInboxRoute,
  AuthenticatedManagerInvestorsRoute: AuthenticatedManagerInvestorsRoute,
  AuthenticatedManagerMemoRoute: AuthenticatedManagerMemoRoute,
  AuthenticatedManagerMessagesRoute: AuthenticatedManagerMessagesRoute,
  AuthenticatedManagerOfferingStatementRoute:
    AuthenticatedManagerOfferingStatementRoute,
  AuthenticatedManagerOnboardingRoute: AuthenticatedManagerOnboardingRoute,
  AuthenticatedManagerPerformanceRoute: AuthenticatedManagerPerformanceRoute,
  AuthenticatedManagerPermissionsRoute: AuthenticatedManagerPermissionsRoute,
  AuthenticatedManagerPortfolioValueRoute:
    AuthenticatedManagerPortfolioValueRoute,
  AuthenticatedManagerProfileRoute: AuthenticatedManagerProfileRoute,
  AuthenticatedManagerPublicPageRoute: AuthenticatedManagerPublicPageRoute,
  AuthenticatedManagerRequestsRoute: AuthenticatedManagerRequestsRoute,
  AuthenticatedManagerTaxRoute: AuthenticatedManagerTaxRoute,
  AuthenticatedManagerTimelineRoute: AuthenticatedManagerTimelineRoute,
  AuthenticatedManagerWiresRoute: AuthenticatedManagerWiresRoute,
  AuthenticatedOnboardingAccreditationRoute:
    AuthenticatedOnboardingAccreditationRoute,
  AuthenticatedOnboardingAmlRoute: AuthenticatedOnboardingAmlRoute,
  AuthenticatedOnboardingDocumentsRoute: AuthenticatedOnboardingDocumentsRoute,
  AuthenticatedOnboardingFundingRoute: AuthenticatedOnboardingFundingRoute,
  AuthenticatedOnboardingKycRoute: AuthenticatedOnboardingKycRoute,
  AuthenticatedOpsBankingRoute: AuthenticatedOpsBankingRoute,
  AuthenticatedOpsSs4Route: AuthenticatedOpsSs4Route,
  AuthenticatedOpsTaxDocumentsRoute: AuthenticatedOpsTaxDocumentsRoute,
  AuthenticatedOpsTeamRoute: AuthenticatedOpsTeamRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedDiligenceIndexRoute: AuthenticatedDiligenceIndexRoute,
  AuthenticatedManagerIndexRoute: AuthenticatedManagerIndexRoute,
  AuthenticatedOpsIndexRoute: AuthenticatedOpsIndexRoute,
  AuthenticatedAdminContractsClientIdRoute:
    AuthenticatedAdminContractsClientIdRoute,
  AuthenticatedAdminFundFundIdRoute: AuthenticatedAdminFundFundIdRoute,
  AuthenticatedAdminPacketFundIdRoute: AuthenticatedAdminPacketFundIdRoute,
  AuthenticatedManagerFundFundIdRoute: AuthenticatedManagerFundFundIdRoute,
  AuthenticatedOpsFundsFundIdRoute: AuthenticatedOpsFundsFundIdRoute,
  AuthenticatedAdminContractsIndexRoute: AuthenticatedAdminContractsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  FundAdministrationRoute: FundAdministrationRoute,
  ManagerLoginRoute: ManagerLoginRoute,
  PlatformRoute: PlatformRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpvRoute: SpvRoute,
  FundSlugRoute: FundSlugRoute,
  ApiPublicLoginAttemptRoute: ApiPublicLoginAttemptRoute,
  LovableEmailEventsRoute: LovableEmailEventsRoute,
  ApiPublicEmailClickRoute: ApiPublicEmailClickRoute,
  ApiPublicEmailOpenRoute: ApiPublicEmailOpenRoute,
  ApiPublicNotifyDrainRoute: ApiPublicNotifyDrainRoute,
  ApiPublicPacketTokenRoute: ApiPublicPacketTokenRoute,
  ApiPublicWebhooksBoxSignRoute: ApiPublicWebhooksBoxSignRoute,
  ApiPublicWebhooksDiditRoute: ApiPublicWebhooksDiditRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
