/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminApplicationIdRouteImport } from './routes/_authenticated/admin.$applicationId'
import { Route as AuthenticatedOnboardingAccreditationRouteImport } from './routes/_authenticated/onboarding.accreditation'
import { Route as AuthenticatedOnboardingAmlRouteImport } from './routes/_authenticated/onboarding.aml'
import { Route as AuthenticatedOnboardingDocumentsRouteImport } from './routes/_authenticated/onboarding.documents'
import { Route as AuthenticatedOnboardingKycRouteImport } from './routes/_authenticated/onboarding.kyc'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminApplicationIdRoute =
  AuthenticatedAdminApplicationIdRouteImport.update({
    id: '/admin/$applicationId',
    path: '/admin/$applicationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingAccreditationRoute =
  AuthenticatedOnboardingAccreditationRouteImport.update({
    id: '/onboarding/accreditation',
    path: '/onboarding/accreditation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingAmlRoute =
  AuthenticatedOnboardingAmlRouteImport.update({
    id: '/onboarding/aml',
    path: '/onboarding/aml',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingDocumentsRoute =
  AuthenticatedOnboardingDocumentsRouteImport.update({
    id: '/onboarding/documents',
    path: '/onboarding/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingKycRoute =
  AuthenticatedOnboardingKycRouteImport.update({
    id: '/onboarding/kyc',
    path: '/onboarding/kyc',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/$applicationId': typeof AuthenticatedAdminApplicationIdRoute
  '/onboarding/accreditation': typeof AuthenticatedOnboardingAccreditationRoute
  '/onboarding/aml': typeof AuthenticatedOnboardingAmlRoute
  '/onboarding/documents': typeof AuthenticatedOnboardingDocumentsRoute
  '/onboarding/kyc': typeof AuthenticatedOnboardingKycRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/$applicationId': typeof AuthenticatedAdminApplicationIdRoute
  '/onboarding/accreditation': typeof AuthenticatedOnboardingAccreditationRoute
  '/onboarding/aml': typeof AuthenticatedOnboardingAmlRoute
  '/onboarding/documents': typeof AuthenticatedOnboardingDocumentsRoute
  '/onboarding/kyc': typeof AuthenticatedOnboardingKycRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/$applicationId': typeof AuthenticatedAdminApplicationIdRoute
  '/_authenticated/onboarding/accreditation': typeof AuthenticatedOnboardingAccreditationRoute
  '/_authenticated/onboarding/aml': typeof AuthenticatedOnboardingAmlRoute
  '/_authenticated/onboarding/documents': typeof AuthenticatedOnboardingDocumentsRoute
  '/_authenticated/onboarding/kyc': typeof AuthenticatedOnboardingKycRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/admin/$applicationId'
    | '/onboarding/accreditation'
    | '/onboarding/aml'
    | '/onboarding/documents'
    | '/onboarding/kyc'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/admin/$applicationId'
    | '/onboarding/accreditation'
    | '/onboarding/aml'
    | '/onboarding/documents'
    | '/onboarding/kyc'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/$applicationId'
    | '/_authenticated/onboarding/accreditation'
    | '/_authenticated/onboarding/aml'
    | '/_authenticated/onboarding/documents'
    | '/_authenticated/onboarding/kyc'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$applicationId': {
      id: '/_authenticated/admin/$applicationId'
      path: '/admin/$applicationId'
      fullPath: '/admin/$applicationId'
      preLoaderRoute: typeof AuthenticatedAdminApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/accreditation': {
      id: '/_authenticated/onboarding/accreditation'
      path: '/onboarding/accreditation'
      fullPath: '/onboarding/accreditation'
      preLoaderRoute: typeof AuthenticatedOnboardingAccreditationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/aml': {
      id: '/_authenticated/onboarding/aml'
      path: '/onboarding/aml'
      fullPath: '/onboarding/aml'
      preLoaderRoute: typeof AuthenticatedOnboardingAmlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/documents': {
      id: '/_authenticated/onboarding/documents'
      path: '/onboarding/documents'
      fullPath: '/onboarding/documents'
      preLoaderRoute: typeof AuthenticatedOnboardingDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/kyc': {
      id: '/_authenticated/onboarding/kyc'
      path: '/onboarding/kyc'
      fullPath: '/onboarding/kyc'
      preLoaderRoute: typeof AuthenticatedOnboardingKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminApplicationIdRoute: typeof AuthenticatedAdminApplicationIdRoute
  AuthenticatedOnboardingAccreditationRoute: typeof AuthenticatedOnboardingAccreditationRoute
  AuthenticatedOnboardingAmlRoute: typeof AuthenticatedOnboardingAmlRoute
  AuthenticatedOnboardingDocumentsRoute: typeof AuthenticatedOnboardingDocumentsRoute
  AuthenticatedOnboardingKycRoute: typeof AuthenticatedOnboardingKycRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminApplicationIdRoute: AuthenticatedAdminApplicationIdRoute,
  AuthenticatedOnboardingAccreditationRoute:
    AuthenticatedOnboardingAccreditationRoute,
  AuthenticatedOnboardingAmlRoute: AuthenticatedOnboardingAmlRoute,
  AuthenticatedOnboardingDocumentsRoute: AuthenticatedOnboardingDocumentsRoute,
  AuthenticatedOnboardingKycRoute: AuthenticatedOnboardingKycRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
